In [118]:
import pandas as pd
import numpy as np
import requests
from tqdm import tqdm
import warnings

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 10)

In [119]:
soil = pd.read_csv("../../data/processed/soil_data_cleaned.csv")

crop = pd.read_csv("../../data/processed/crop_production_cleaned.csv")

coords = pd.read_csv("../../data/processed/district_registry_geocoded.csv")

In [120]:
print("="*60)
print("SOIL DATA")
print("="*60)
print(soil.shape)
display(soil.head())

print("="*60)
print("CROP DATA")
print("="*60)
print(crop.shape)
display(crop.head())

print("="*60)
print("COORDINATE DATA")
print("="*60)
print(coords.shape)
display(coords.head())

============================================================
SOIL DATA
============================================================
(10853209, 14)

,id,year,state_name,state_code,district_name,district_code,block_name,block_code,village_name,village_code,nutrient_type,nutrient_name,nutrient_level,value
0,3107023,2023-24,Uttarakhand,5,Udham Singh Nagar,56,Rudrapur,439,Malsi,55943,Micro,Copper,Deficient,0
1,3107024,2023-24,Uttarakhand,5,Udham Singh Nagar,56,Rudrapur,439,Malsi,55943,Micro,Copper,Sufficient,85
2,3107025,2023-24,Uttarakhand,5,Udham Singh Nagar,56,Rudrapur,439,Malsi,55943,Micro,Iron,Deficient,0
3,3107026,2023-24,Uttarakhand,5,Udham Singh Nagar,56,Rudrapur,439,Malsi,55943,Micro,Iron,Sufficient,85
4,3107027,2023-24,Uttarakhand,5,Udham Singh Nagar,56,Rudrapur,439,Malsi,55943,Micro,Manganese,Deficient,2

============================================================
CROP DATA
============================================================
(246091, 8)

,index,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0

============================================================
COORDINATE DATA
============================================================
(652, 4)

                    State_Name             District_Name   latitude  longitude
0  Andaman and Nicobar Islands                  NICOBARS   9.150000  92.750000
1  Andaman and Nicobar Islands  NORTH AND MIDDLE ANDAMAN  12.611239  92.831654
2  Andaman and Nicobar Islands            SOUTH ANDAMANS  11.620000  92.730000
3               Andhra Pradesh                 ANANTAPUR  14.678322  77.606504
4               Andhra Pradesh                  CHITTOOR  13.325036  79.648061

In [121]:
print("SOIL COLUMNS")
print(soil.columns.tolist())

print()

print("CROP COLUMNS")
print(crop.columns.tolist())

print()

print("COORDINATE COLUMNS")
print(coords.columns.tolist())

SOIL COLUMNS
['id', 'year', 'state_name', 'state_code', 'district_name', 'district_code', 'block_name', 'block_code', 'village_name', 'village_code', 'nutrient_type', 'nutrient_name', 'nutrient_level', 'value']

CROP COLUMNS
['index', 'State_Name', 'District_Name', 'Crop_Year', 'Season', 'Crop', 'Area', 'Production']

COORDINATE COLUMNS
['State_Name', 'District_Name', 'latitude', 'longitude']

In [122]:
print("SOIL")

display(soil.isnull().sum())

print()

print("CROP")

display(crop.isnull().sum())

print()

print("COORDINATES")

display(coords.isnull().sum())

SOIL

id                0
year              0
state_name        0
state_code        0
district_name     0
                 ..
village_code      0
nutrient_type     0
nutrient_name     0
nutrient_level    0
value             0
Length: 14, dtype: int64

CROP

index               0
State_Name          0
District_Name       0
Crop_Year           0
Season              0
Crop                0
Area                0
Production       3730
dtype: int64

COORDINATES

State_Name       0
District_Name    0
latitude         0
longitude        0
dtype: int64

In [123]:
soil["nutrient_name"].value_counts()

nutrient_name
Organic Carbon             1122793
Phosphorus                 1122778
Potassium                  1122777
Nitrogen                   1122703
Soil Ph                    1122664
                            ...
Iron                        748501
Sulphur                     748491
Copper                      748490
Boron                       748479
Electrical Conductivity     748475
Name: count, Length: 12, dtype: int64

In [124]:
soil["value"].describe()

count    1.085321e+07
mean     1.409020e+01
std      4.490956e+01
min      0.000000e+00
25%      0.000000e+00
50%      2.000000e+00
75%      1.100000e+01
max      1.020500e+04
Name: value, dtype: float64

In [125]:
# Keep only the required columns
soil = soil[
    [
        "state_name",
        "district_name",
        "nutrient_name",
        "value"
    ]
].copy()

print(soil.shape)
soil.head()

(10853209, 4)

    state_name      district_name nutrient_name  value
0  Uttarakhand  Udham Singh Nagar        Copper      0
1  Uttarakhand  Udham Singh Nagar        Copper     85
2  Uttarakhand  Udham Singh Nagar          Iron      0
3  Uttarakhand  Udham Singh Nagar          Iron     85
4  Uttarakhand  Udham Singh Nagar     Manganese      2

In [126]:
soil.isnull().sum()

state_name       0
district_name    0
nutrient_name    0
value            0
dtype: int64

In [127]:
soil_avg = (
    soil
    .groupby(
        ["state_name", "district_name", "nutrient_name"],
        as_index=False
    )["value"]
    .mean()
)

soil_avg.head()

,state_name,district_name,nutrient_name,value
0,Andaman And Nicobar Islands,Nicobars,Boron,7.070796
1,Andaman And Nicobar Islands,Nicobars,Copper,7.070796
2,Andaman And Nicobar Islands,Nicobars,Electrical Conductivity,7.008772
3,Andaman And Nicobar Islands,Nicobars,Iron,7.070796
4,Andaman And Nicobar Islands,Nicobars,Manganese,7.070796

In [128]:
soil_profile = (
    soil_avg
    .pivot(
        index=["state_name", "district_name"],
        columns="nutrient_name",
        values="value"
    )
    .reset_index()
)

soil_profile.head()

nutrient_name,state_name,district_name,Boron,Copper,Electrical Conductivity,Iron,Manganese,Nitrogen,Organic Carbon,Phosphorus,Potassium,Soil Ph,Sulphur,Zinc
0,Andaman And Nicobar Islands,Nicobars,7.070796,7.070796,7.008772,7.070796,7.070796,4.727811,4.727811,4.727811,4.727811,4.727811,7.070796,7.070796
1,Andaman And Nicobar Islands,North And Middle Andaman,30.027523,30.022936,30.022936,30.027523,30.027523,20.018349,20.018349,20.018349,20.018349,20.018349,30.027523,30.027523
2,Andaman And Nicobar Islands,South Andamans,16.793814,16.793814,16.793814,16.793814,16.793814,11.195876,11.192440,11.195876,11.195876,11.195876,16.793814,16.793814
3,Andhra Pradesh,Alluri Sitharama Raju,4.039506,4.042222,3.995309,4.039506,4.043457,2.685761,2.670453,2.688889,2.690864,2.645267,4.039506,4.035062
4,Andhra Pradesh,Anakapalli,13.856935,13.548012,13.852085,13.529098,13.508729,9.231490,9.234400,9.246363,9.238927,9.229227,13.859845,13.441319

In [129]:
print("District Soil Profile Shape:")
print(soil_profile.shape)

print()

print("Columns:")
print(soil_profile.columns.tolist())

District Soil Profile Shape:
(738, 14)

Columns:
['state_name', 'district_name', 'Boron', 'Copper', 'Electrical Conductivity', 'Iron', 'Manganese', 'Nitrogen', 'Organic Carbon', 'Phosphorus', 'Potassium', 'Soil Ph', 'Sulphur', 'Zinc']

In [130]:
soil_profile.to_csv(
    "../../data/processed/district_soil_profile.csv",
    index=False
)

print("✅ District soil profile saved successfully.")

✅ District soil profile saved successfully.

In [131]:
# Crop dataset
crop = crop.rename(columns={
    "State_Name": "state_name",
    "District_Name": "district_name",
    "Crop_Year": "year",
    "Crop": "crop",
    "Season": "season",
    "Area": "area",
    "Production": "production",
    "yield": "yield"
})

# Remove extra spaces and convert to uppercase for reliable matching
crop["state_name"] = crop["state_name"].str.strip().str.upper()
crop["district_name"] = crop["district_name"].str.strip().str.upper()

soil_profile["state_name"] = soil_profile["state_name"].str.strip().str.upper()
soil_profile["district_name"] = soil_profile["district_name"].str.strip().str.upper()

print("Crop:", crop.shape)
print("Soil:", soil_profile.shape)

Crop: (246091, 8)
Soil: (738, 14)

In [132]:
master = crop.merge(
    soil_profile,
    on=["state_name", "district_name"],
    how="left"
)

print("Master Shape:", master.shape)

master.head()

Master Shape: (246091, 20)

,index,state_name,district_name,year,season,crop,area,production,Boron,Copper,Electrical Conductivity,Iron,Manganese,Nitrogen,Organic Carbon,Phosphorus,Potassium,Soil Ph,Sulphur,Zinc
0,0,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0,7.070796,7.070796,7.008772,7.070796,7.070796,4.727811,4.727811,4.727811,4.727811,4.727811,7.070796,7.070796
1,1,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0,7.070796,7.070796,7.008772,7.070796,7.070796,4.727811,4.727811,4.727811,4.727811,4.727811,7.070796,7.070796
2,2,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,2000,Kharif,Rice,102.0,321.0,7.070796,7.070796,7.008772,7.070796,7.070796,4.727811,4.727811,4.727811,4.727811,4.727811,7.070796,7.070796
3,3,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,2000,Whole Year,Banana,176.0,641.0,7.070796,7.070796,7.008772,7.070796,7.070796,4.727811,4.727811,4.727811,4.727811,4.727811,7.070796,7.070796
4,4,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0,7.070796,7.070796,7.008772,7.070796,7.070796,4.727811,4.727811,4.727811,4.727811,4.727811,7.070796,7.070796

In [133]:
print("Missing values after merge:")

master[
    [
        "Nitrogen",
        "Phosphorus",
        "Potassium",
        "Organic Carbon",
        "Soil Ph"
    ]
].isnull().sum()

Missing values after merge:

Nitrogen          38405
Phosphorus        38405
Potassium         38405
Organic Carbon    38405
Soil Ph           38405
dtype: int64

In [134]:
print("Total crop records:", len(master))

matched = master["Nitrogen"].notna().sum()

print("Matched records:", matched)
print("Coverage:", round((matched / len(master)) * 100, 2), "%")

Total crop records: 246091
Matched records: 207686
Coverage: 84.39 %

In [135]:
print(sorted(crop["year"].unique()))

[np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015)]

In [136]:
unmatched = master[master["Nitrogen"].isna()].copy()

print("Unmatched Records:", len(unmatched))

unmatched_districts = (
    unmatched[["state_name", "district_name"]]
    .drop_duplicates()
    .sort_values(["state_name", "district_name"])
)

print("Unique Unmatched Districts:", len(unmatched_districts))

unmatched_districts.head(20)

Unmatched Records: 38405
Unique Unmatched Districts: 94

              state_name    district_name
203       ANDHRA PRADESH        ANANTAPUR
3232      ANDHRA PRADESH           KADAPA
6328      ANDHRA PRADESH     SPSR NELLORE
7699      ANDHRA PRADESH   VISAKHAPATANAM
21468              ASSAM        KARIMGANJ
...                  ...              ...
66801            HARYANA          GURGAON
69109            HARYANA            MEWAT
72697   HIMACHAL PRADESH  LAHUL AND SPITI
74057  JAMMU AND KASHMIR           BADGAM
74565  JAMMU AND KASHMIR           KARGIL

[20 rows x 2 columns]

In [137]:
unmatched = master[master["Nitrogen"].isna()].copy()

print("Unmatched Records:", len(unmatched))

Unmatched Records: 38405

In [138]:
unmatched_districts = (
    unmatched[["state_name", "district_name"]]
    .drop_duplicates()
    .sort_values(["state_name", "district_name"])
    .reset_index(drop=True)
)

print("Unique unmatched districts:", len(unmatched_districts))

unmatched_districts.head(20)

Unique unmatched districts: 94

           state_name    district_name
0      ANDHRA PRADESH        ANANTAPUR
1      ANDHRA PRADESH           KADAPA
2      ANDHRA PRADESH     SPSR NELLORE
3      ANDHRA PRADESH   VISAKHAPATANAM
4               ASSAM        KARIMGANJ
..                ...              ...
15            HARYANA          GURGAON
16            HARYANA            MEWAT
17   HIMACHAL PRADESH  LAHUL AND SPITI
18  JAMMU AND KASHMIR           BADGAM
19  JAMMU AND KASHMIR           KARGIL

[20 rows x 2 columns]

In [139]:
soil_profile[
    soil_profile["district_name"].str.upper() == "ADILABAD"
]

nutrient_name,state_name,district_name,Boron,Copper,Electrical Conductivity,Iron,Manganese,Nitrogen,Organic Carbon,Phosphorus,Potassium,Soil Ph,Sulphur,Zinc
588,TELANGANA,ADILABAD,111.7,50.98,111.96,50.98,50.98,74.64,74.64,74.64,74.626667,74.626667,111.76,50.98

In [140]:
soil_profile["district_name"].value_counts().head(20)

district_name
BILASPUR                    2
HAMIRPUR                    2
PRATAPGARH                  2
NICOBARS                    1
NORTH AND MIDDLE ANDAMAN    1
                           ..
GUNTUR                      1
KAKINADA                    1
KRISHNA                     1
KURNOOL                     1
NANDYAL                     1
Name: count, Length: 20, dtype: int64

In [141]:
# Soil profile using only district name
soil_by_district = soil_profile.drop(columns=["state_name"])

# Try matching only the unmatched records
unmatched_recovered = unmatched.drop(
    columns=soil_profile.columns[2:],  # remove empty soil columns
    errors="ignore"
).merge(
    soil_by_district,
    on="district_name",
    how="left"
)

print(unmatched_recovered.shape)

print("Recovered Records:",
      unmatched_recovered["Nitrogen"].notna().sum())

print("Still Unmatched:",
      unmatched_recovered["Nitrogen"].isna().sum())

(38405, 20)
Recovered Records: 1400
Still Unmatched: 37005

In [142]:
# Find district names that appear exactly once
unique_districts = (
    soil_profile["district_name"]
    .value_counts()
)

unique_districts = unique_districts[unique_districts == 1].index

print("Unique district names:", len(unique_districts))

Unique district names: 732

In [143]:
# Keep only districts that occur exactly once
soil_unique = soil_profile[
    soil_profile["district_name"].isin(unique_districts)
].copy()

print(soil_unique.shape)

(732, 14)

In [144]:
# Remove the empty soil columns from unmatched records
soil_columns = [
    "Boron",
    "Copper",
    "Electrical Conductivity",
    "Iron",
    "Manganese",
    "Nitrogen",
    "Organic Carbon",
    "Phosphorus",
    "Potassium",
    "Soil Ph",
    "Sulphur",
    "Zinc"
]

unmatched_clean = unmatched.drop(columns=soil_columns, errors="ignore")

# Recover using only unique district names
recovered = unmatched_clean.merge(
    soil_unique.drop(columns=["state_name"]),
    on="district_name",
    how="left"
)

print("Recovered Shape:", recovered.shape)
print("Recovered Records:", recovered["Nitrogen"].notna().sum())
print("Still Missing:", recovered["Nitrogen"].isna().sum())

Recovered Shape: (38405, 20)
Recovered Records: 1400
Still Missing: 37005

In [145]:
# Keep only the records that were recovered successfully
recovered_success = recovered[recovered["Nitrogen"].notna()].copy()

# Keep the original matched records
master_matched = master[master["Nitrogen"].notna()].copy()

# Combine them
master_final = pd.concat(
    [master_matched, recovered_success],
    ignore_index=True
)

print("Final Dataset Shape:", master_final.shape)
print("Coverage:", round(len(master_final) / len(crop) * 100, 2), "%")

Final Dataset Shape: (209086, 20)
Coverage: 84.96 %

In [146]:
master_final.to_csv(
    "../../data/processed/master_soil_crop_v2.csv",
    index=False
)

## Weather

In [147]:
weather_requests = (
    master_final[
        ["state_name", "district_name", "year"]
    ]
    .drop_duplicates()
    .sort_values(
        ["state_name", "district_name", "year"]
    )
    .reset_index(drop=True)
)

print(weather_requests.shape)

weather_requests.head()

(8467, 3)

                    state_name district_name  year
0  ANDAMAN AND NICOBAR ISLANDS      NICOBARS  2000
1  ANDAMAN AND NICOBAR ISLANDS      NICOBARS  2001
2  ANDAMAN AND NICOBAR ISLANDS      NICOBARS  2002
3  ANDAMAN AND NICOBAR ISLANDS      NICOBARS  2003
4  ANDAMAN AND NICOBAR ISLANDS      NICOBARS  2004

In [148]:
coords = pd.read_csv("../../data/processed/district_registry_geocoded.csv")

print(coords.columns.tolist())

print(coords.head())

['State_Name', 'District_Name', 'latitude', 'longitude']
                    State_Name             District_Name   latitude  longitude
0  Andaman and Nicobar Islands                  NICOBARS   9.150000  92.750000
1  Andaman and Nicobar Islands  NORTH AND MIDDLE ANDAMAN  12.611239  92.831654
2  Andaman and Nicobar Islands            SOUTH ANDAMANS  11.620000  92.730000
3               Andhra Pradesh                 ANANTAPUR  14.678322  77.606504
4               Andhra Pradesh                  CHITTOOR  13.325036  79.648061

In [149]:
print(coords[["latitude", "longitude"]].isna().sum())

print()

print("Rows with coordinates:",
      coords.dropna(subset=["latitude", "longitude"]).shape[0])

print("Total rows:",
      len(coords))

latitude     0
longitude    0
dtype: int64

Rows with coordinates: 652
Total rows: 652

In [150]:
import os

for file in os.listdir("../../data/processed"):
    print(file)

crop_production_cleaned.csv
district_crop_database.csv
district_crop_database_standardized.csv
district_manual_mapping.csv
district_matching_report.csv
district_registry.csv
district_registry_geocoded.csv
district_soil_database.csv
district_soil_profile.csv
master_soil_crop_v2.csv
missing_district_coordinates.csv
soil_data_cleaned.csv
weather_districts.csv
weather_yearly.csv

In [151]:
gadm = pd.read_csv(
    "../../data/processed/district_registry_geocoded.csv"
)

print(gadm.shape)
print(gadm.columns.tolist())

gadm.head()

(652, 4)
['State_Name', 'District_Name', 'latitude', 'longitude']

                    State_Name             District_Name   latitude  longitude
0  Andaman and Nicobar Islands                  NICOBARS   9.150000  92.750000
1  Andaman and Nicobar Islands  NORTH AND MIDDLE ANDAMAN  12.611239  92.831654
2  Andaman and Nicobar Islands            SOUTH ANDAMANS  11.620000  92.730000
3               Andhra Pradesh                 ANANTAPUR  14.678322  77.606504
4               Andhra Pradesh                  CHITTOOR  13.325036  79.648061

In [152]:
print("master_final columns:")
print(master_final.columns.tolist())

master_final columns:
['index', 'state_name', 'district_name', 'year', 'season', 'crop', 'area', 'production', 'Boron', 'Copper', 'Electrical Conductivity', 'Iron', 'Manganese', 'Nitrogen', 'Organic Carbon', 'Phosphorus', 'Potassium', 'Soil Ph', 'Sulphur', 'Zinc']

In [153]:
print("gadm columns:")
print(gadm.columns.tolist())

gadm columns:
['State_Name', 'District_Name', 'latitude', 'longitude']

In [154]:
master_final["State_Name"] = (
    master_final["state_name"]
    .astype(str)
    .str.strip()
    .str.upper()
)

master_final["District_Name"] = (
    master_final["district_name"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [155]:
# Standardize names
gadm["State_Name"] = gadm["State_Name"].str.strip().str.upper()
gadm["District_Name"] = gadm["District_Name"].str.strip().str.upper()

# Merge with our master dataset
weather_base = master_final.merge(
    gadm,
    on=["State_Name", "District_Name"],
    how="left"
)

print("Master Shape:", weather_base.shape)

print("Rows with Coordinates:",
      weather_base.dropna(subset=["latitude", "longitude"]).shape[0])

print("Coverage:",
      round(
          weather_base["latitude"].notna().mean() * 100,
          2
      ),
      "%"
)

Master Shape: (209086, 24)
Rows with Coordinates: 209086
Coverage: 100.0 %

In [156]:
weather_districts = (
    weather_base[
        ["state_name", "district_name", "latitude", "longitude"]
    ]
    .dropna()
    .drop_duplicates()
    .reset_index(drop=True)
)

In [157]:
# Create one request per district

weather_districts = (
    weather_base[
        [
            "state_name",
            "district_name",
            "latitude",
            "longitude"
        ]
    ]
    .dropna(subset=["latitude", "longitude"])
    .drop_duplicates()
    .sort_values(["state_name", "district_name"])
    .reset_index(drop=True)
)

print("Unique districts:", len(weather_districts))

weather_districts.head()

Unique districts: 563

                    state_name             district_name   latitude  longitude
0  ANDAMAN AND NICOBAR ISLANDS                  NICOBARS   9.150000  92.750000
1  ANDAMAN AND NICOBAR ISLANDS  NORTH AND MIDDLE ANDAMAN  12.611239  92.831654
2  ANDAMAN AND NICOBAR ISLANDS            SOUTH ANDAMANS  11.620000  92.730000
3               ANDHRA PRADESH                  CHITTOOR  13.325036  79.648061
4               ANDHRA PRADESH             EAST GODAVARI  16.995664  81.715438

In [158]:
weather_districts.to_csv(
    "../../data/processed/weather_districts.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!

In [159]:
import requests
import pandas as pd
from pathlib import Path

In [178]:
district = weather_districts.iloc[0]

lat = district["latitude"]
lon = district["longitude"]

print("District :", district["district_name"])
print("State    :", district["state_name"])
print("Latitude :", lat)
print("Longitude:", lon)

District : NICOBARS
State    : ANDAMAN AND NICOBAR ISLANDS
Latitude : 9.15
Longitude: 92.75

In [179]:
import requests
import pandas as pd

lat = 9.15
lon = 92.75

url = (
    "https://power.larc.nasa.gov/api/temporal/daily/point"
    f"?parameters=T2M,PRECTOTCORR,RH2M,WS2M,ALLSKY_SFC_SW_DWN"
    f"&community=AG"
    f"&latitude={lat}"
    f"&longitude={lon}"
    f"&start=19970101"
    f"&end=20201231"
    f"&format=JSON"
)

response = requests.get(url, timeout=60)

print("Status Code:", response.status_code)

data = response.json()

print(data.keys())

Status Code: 200
dict_keys(['type', 'geometry', 'properties', 'header', 'messages', 'parameters', 'times'])

In [176]:
import requests
import pandas as pd
from pathlib import Path
from time import sleep

# -----------------------------------
# Paths
# -----------------------------------

REGISTRY_PATH = Path(
    "../../data/processed/district_registry_geocoded.csv"
)

OUTPUT_DIR = Path(
    "../../data/weather"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# -----------------------------------
# Load district registry
# -----------------------------------

districts = pd.read_csv(REGISTRY_PATH)

# Clean names
districts["State_Name"] = (
    districts["State_Name"]
    .astype(str)
    .str.strip()
)

districts["District_Name"] = (
    districts["District_Name"]
    .astype(str)
    .str.strip()
)

print("Total districts:", len(districts))

# -----------------------------------
# NASA POWER download
# -----------------------------------

for index, row in districts.iterrows():

    state = row["State_Name"]
    district = row["District_Name"]

    lat = row["latitude"]
    lon = row["longitude"]

    # Filename
    filename = (
        f"{state}_{district}"
        .upper()
        .replace(" ", "_")
        .replace("/", "_")
        .replace("(", "")
        .replace(")", "")
        .replace("&", "AND")
        + ".csv"
    )

    output_file = OUTPUT_DIR / filename

    # --------------------------------
    # Skip already downloaded files
    # --------------------------------

    if output_file.exists():

        print(
            f"[{index + 1}/{len(districts)}] "
            f"Already exists: {district}"
        )

        continue

    print(
        f"[{index + 1}/{len(districts)}] "
        f"Downloading: {state} - {district}"
    )

    # --------------------------------
    # NASA POWER URL
    # --------------------------------

    url = (
        "https://power.larc.nasa.gov/api/temporal/daily/point"
        "?parameters=T2M,PRECTOTCORR,RH2M,WS2M,ALLSKY_SFC_SW_DWN"
        "&community=AG"
        f"&latitude={lat}"
        f"&longitude={lon}"
        "&start=19970101"
        "&end=20201231"
        "&format=JSON"
    )

    try:

        response = requests.get(
            url,
            timeout=60
        )

        response.raise_for_status()

        data = response.json()

        # --------------------------------
        # Extract parameters
        # --------------------------------

        parameters = data[
            "properties"
        ][
            "parameter"
        ]

        weather_df = pd.DataFrame(
            parameters
        )

        weather_df.index.name = "date"

        weather_df.reset_index(
            inplace=True
        )

        # --------------------------------
        # Add location information
        # --------------------------------

        weather_df["State_Name"] = state
        weather_df["District_Name"] = district
        weather_df["latitude"] = lat
        weather_df["longitude"] = lon

        # --------------------------------
        # Save
        # --------------------------------

        weather_df.to_csv(
            output_file,
            index=False
        )

        print(
            f"   ✓ Saved {len(weather_df)} rows"
        )

    except Exception as e:

        print(
            f"   ✗ Failed: {district}"
        )

        print(
            f"     Error: {e}"
        )



print("\nDownload process completed.")

Total districts: 652
[1/652] Already exists: NICOBARS
[2/652] Already exists: NORTH AND MIDDLE ANDAMAN
[3/652] Already exists: SOUTH ANDAMANS
[4/652] Already exists: ANANTAPUR
[5/652] Already exists: CHITTOOR
[6/652] Already exists: EAST GODAVARI
[7/652] Already exists: GUNTUR
[8/652] Already exists: KADAPA
[9/652] Already exists: KRISHNA
[10/652] Already exists: KURNOOL
[11/652] Already exists: PRAKASAM
[12/652] Already exists: SPSR NELLORE
[13/652] Already exists: SRIKAKULAM
[14/652] Already exists: VISAKHAPATANAM
[15/652] Already exists: VIZIANAGARAM
[16/652] Already exists: WEST GODAVARI
[17/652] Already exists: ANJAW
[18/652] Already exists: CHANGLANG
[19/652] Already exists: DIBANG VALLEY
[20/652] Already exists: EAST KAMENG
[21/652] Already exists: EAST SIANG
[22/652] Already exists: KURUNG KUMEY
[23/652] Already exists: LOHIT
[24/652] Already exists: LONGDING
[25/652] Already exists: LOWER DIBANG VALLEY
[26/652] Already exists: LOWER SUBANSIRI
[27/652] Already exists: NAMSAI
[28/652] Already exists: PAPUM PARE
[29/652] Already exists: TAWANG
[30/652] Already exists: TIRAP
[31/652] Already exists: UPPER SIANG
[32/652] Already exists: UPPER SUBANSIRI
[33/652] Already exists: WEST KAMENG
[34/652] Already exists: WEST SIANG
[35/652] Already exists: BAKSA
[36/652] Already exists: BARPETA
[37/652] Already exists: BONGAIGAON
[38/652] Already exists: CACHAR
[39/652] Already exists: CHIRANG
[40/652] Already exists: DARRANG
[41/652] Already exists: DHEMAJI
[42/652] Already exists: DHUBRI
[43/652] Already exists: DIBRUGARH
[44/652] Already exists: DIMA HASAO
[45/652] Already exists: GOALPARA
[46/652] Already exists: GOLAGHAT
[47/652] Already exists: HAILAKANDI
[48/652] Already exists: JORHAT
[49/652] Already exists: KAMRUP
[50/652] Already exists: KAMRUP METRO
[51/652] Already exists: KARBI ANGLONG
[52/652] Already exists: KARIMGANJ
[53/652] Already exists: KOKRAJHAR
[54/652] Already exists: LAKHIMPUR
[55/652] Already exists: MARIGAON
[56/652] Already exists: NAGAON
[57/652] Already exists: NALBARI
[58/652] Already exists: SIVASAGAR
[59/652] Already exists: SONITPUR
[60/652] Already exists: TINSUKIA
[61/652] Already exists: UDALGURI
[62/652] Already exists: ARARIA
[63/652] Already exists: ARWAL
[64/652] Already exists: AURANGABAD
[65/652] Already exists: BANKA
[66/652] Already exists: BEGUSARAI
[67/652] Already exists: BHAGALPUR
[68/652] Already exists: BHOJPUR
[69/652] Already exists: BUXAR
[70/652] Already exists: DARBHANGA
[71/652] Already exists: GAYA
[72/652] Already exists: GOPALGANJ
[73/652] Already exists: JAMUI
[74/652] Already exists: JEHANABAD
[75/652] Already exists: KAIMUR (BHABUA)
[76/652] Already exists: KATIHAR
[77/652] Already exists: KHAGARIA
[78/652] Already exists: KISHANGANJ
[79/652] Already exists: LAKHISARAI
[80/652] Already exists: MADHEPURA
[81/652] Already exists: MADHUBANI
[82/652] Already exists: MUNGER
[83/652] Already exists: MUZAFFARPUR
[84/652] Already exists: NALANDA
[85/652] Already exists: NAWADA
[86/652] Already exists: PASHCHIM CHAMPARAN
[87/652] Already exists: PATNA
[88/652] Already exists: PURBI CHAMPARAN
[89/652] Already exists: PURNIA
[90/652] Already exists: ROHTAS
[91/652] Already exists: SAHARSA
[92/652] Already exists: SAMASTIPUR
[93/652] Already exists: SARAN
[94/652] Already exists: SHEIKHPURA
[95/652] Already exists: SHEOHAR
[96/652] Already exists: SITAMARHI
[97/652] Already exists: SIWAN
[98/652] Already exists: SUPAUL
[99/652] Already exists: VAISHALI
[100/652] Already exists: CHANDIGARH
[101/652] Already exists: BALOD
[102/652] Already exists: BALODA BAZAR
[103/652] Already exists: BALRAMPUR
[104/652] Already exists: BASTAR
[105/652] Already exists: BEMETARA
[106/652] Already exists: BIJAPUR
[107/652] Already exists: BILASPUR
[108/652] Already exists: DANTEWADA
[109/652] Already exists: DHAMTARI
[110/652] Already exists: DURG
[111/652] Already exists: GARIYABAND
[112/652] Already exists: JANJGIR-CHAMPA
[113/652] Already exists: JASHPUR
[114/652] Already exists: KABIRDHAM
[115/652] Already exists: KANKER
[116/652] Already exists: KONDAGAON
[117/652] Already exists: KORBA
[118/652] Already exists: KOREA
[119/652] Already exists: MAHASAMUND
[120/652] Already exists: MUNGELI
[121/652] Already exists: NARAYANPUR
[122/652] Already exists: RAIGARH
[123/652] Already exists: RAIPUR
[124/652] Already exists: RAJNANDGAON
[125/652] Already exists: SUKMA
[126/652] Already exists: SURAJPUR
[127/652] Already exists: SURGUJA
[128/652] Already exists: DADRA AND NAGAR HAVELI
[129/652] Already exists: NORTH GOA
[130/652] Already exists: SOUTH GOA
[131/652] Already exists: AHMADABAD
[132/652] Already exists: AMRELI
[133/652] Already exists: ANAND
[134/652] Already exists: BANAS KANTHA
[135/652] Already exists: BHARUCH
[136/652] Already exists: BHAVNAGAR
[137/652] Already exists: DANG
[138/652] Already exists: DOHAD
[139/652] Already exists: GANDHINAGAR
[140/652] Already exists: JAMNAGAR
[141/652] Already exists: JUNAGADH
[142/652] Already exists: KACHCHH
[143/652] Already exists: KHEDA
[144/652] Already exists: MAHESANA
[145/652] Already exists: NARMADA
[146/652] Already exists: NAVSARI
[147/652] Already exists: PANCH MAHALS
[148/652] Already exists: PATAN
[149/652] Already exists: PORBANDAR
[150/652] Already exists: RAJKOT
[151/652] Already exists: SABAR KANTHA
[152/652] Already exists: SURAT
[153/652] Already exists: SURENDRANAGAR
[154/652] Already exists: TAPI
[155/652] Already exists: VADODARA
[156/652] Already exists: VALSAD
[157/652] Already exists: AMBALA
[158/652] Already exists: BHIWANI
[159/652] Already exists: FARIDABAD
[160/652] Already exists: FATEHABAD
[161/652] Already exists: GURGAON
[162/652] Already exists: HISAR
[163/652] Already exists: JHAJJAR
[164/652] Already exists: JIND
[165/652] Already exists: KAITHAL
[166/652] Already exists: KARNAL
[167/652] Already exists: KURUKSHETRA
[168/652] Already exists: MAHENDRAGARH
[169/652] Already exists: MEWAT
[170/652] Already exists: PALWAL
[171/652] Already exists: PANCHKULA
[172/652] Already exists: PANIPAT
[173/652] Already exists: REWARI
[174/652] Already exists: ROHTAK
[175/652] Already exists: SIRSA
[176/652] Already exists: SONIPAT
[177/652] Already exists: YAMUNANAGAR
[178/652] Already exists: BILASPUR
[179/652] Already exists: CHAMBA
[180/652] Already exists: HAMIRPUR
[181/652] Already exists: KANGRA
[182/652] Already exists: KINNAUR
[183/652] Already exists: KULLU
[184/652] Already exists: LAHUL AND SPITI
[185/652] Already exists: MANDI
[186/652] Already exists: SHIMLA
[187/652] Already exists: SIRMAUR
[188/652] Already exists: SOLAN
[189/652] Already exists: UNA
[190/652] Already exists: ANANTNAG
[191/652] Already exists: BADGAM
[192/652] Already exists: BANDIPORA
[193/652] Already exists: BARAMULLA
[194/652] Already exists: DODA
[195/652] Already exists: GANDERBAL
[196/652] Already exists: JAMMU
[197/652] Already exists: KARGIL
[198/652] Already exists: KATHUA
[199/652] Already exists: KISHTWAR
[200/652] Already exists: KULGAM
[201/652] Already exists: KUPWARA
[202/652] Already exists: LEH LADAKH
[203/652] Already exists: POONCH
[204/652] Already exists: PULWAMA
[205/652] Already exists: RAJAURI
[206/652] Already exists: RAMBAN
[207/652] Already exists: REASI
[208/652] Already exists: SAMBA
[209/652] Already exists: SHOPIAN
[210/652] Already exists: SRINAGAR
[211/652] Already exists: UDHAMPUR
[212/652] Already exists: BOKARO
[213/652] Already exists: CHATRA
[214/652] Already exists: DEOGHAR
[215/652] Already exists: DHANBAD
[216/652] Already exists: DUMKA
[217/652] Already exists: EAST SINGHBUM
[218/652] Already exists: GARHWA
[219/652] Already exists: GIRIDIH
[220/652] Already exists: GODDA
[221/652] Already exists: GUMLA
[222/652] Already exists: HAZARIBAGH
[223/652] Already exists: JAMTARA
[224/652] Already exists: KHUNTI
[225/652] Already exists: KODERMA
[226/652] Already exists: LATEHAR
[227/652] Already exists: LOHARDAGA
[228/652] Already exists: PAKUR
[229/652] Already exists: PALAMU
[230/652] Already exists: RAMGARH
[231/652] Already exists: RANCHI
[232/652] Already exists: SAHEBGANJ
[233/652] Already exists: SARAIKELA KHARSAWAN
[234/652] Already exists: SIMDEGA
[235/652] Already exists: WEST SINGHBHUM
[236/652] Already exists: BAGALKOT
[237/652] Already exists: BANGALORE RURAL
[238/652] Already exists: BELGAUM
[239/652] Already exists: BELLARY
[240/652] Already exists: BENGALURU URBAN
[241/652] Already exists: BIDAR
[242/652] Already exists: BIJAPUR
[243/652] Already exists: CHAMARAJANAGAR
[244/652] Already exists: CHIKBALLAPUR
[245/652] Already exists: CHIKMAGALUR
[246/652] Already exists: CHITRADURGA
[247/652] Already exists: DAKSHIN KANNAD
[248/652] Already exists: DAVANGERE
[249/652] Already exists: DHARWAD
[250/652] Already exists: GADAG
[251/652] Already exists: GULBARGA
[252/652] Already exists: HASSAN
[253/652] Already exists: HAVERI
[254/652] Already exists: KODAGU
[255/652] Already exists: KOLAR
[256/652] Already exists: KOPPAL
[257/652] Already exists: MANDYA
[258/652] Already exists: MYSORE
[259/652] Already exists: RAICHUR
[260/652] Already exists: RAMANAGARA
[261/652] Already exists: SHIMOGA
[262/652] Already exists: TUMKUR
[263/652] Already exists: UDUPI
[264/652] Already exists: UTTAR KANNAD
[265/652] Already exists: YADGIR
[266/652] Already exists: ALAPPUZHA
[267/652] Already exists: ERNAKULAM
[268/652] Already exists: IDUKKI
[269/652] Already exists: KANNUR
[270/652] Already exists: KASARAGOD
[271/652] Already exists: KOLLAM
[272/652] Already exists: KOTTAYAM
[273/652] Already exists: KOZHIKODE
[274/652] Already exists: MALAPPURAM
[275/652] Already exists: PALAKKAD
[276/652] Already exists: PATHANAMTHITTA
[277/652] Already exists: THIRUVANANTHAPURAM
[278/652] Already exists: THRISSUR
[279/652] Already exists: WAYANAD
[280/652] Already exists: AGAR MALWA
[281/652] Already exists: ALIRAJPUR
[282/652] Already exists: ANUPPUR
[283/652] Already exists: ASHOKNAGAR
[284/652] Already exists: BALAGHAT
[285/652] Already exists: BARWANI
[286/652] Already exists: BETUL
[287/652] Already exists: BHIND
[288/652] Already exists: BHOPAL
[289/652] Already exists: BURHANPUR
[290/652] Already exists: CHHATARPUR
[291/652] Already exists: CHHINDWARA
[292/652] Already exists: DAMOH
[293/652] Already exists: DATIA
[294/652] Already exists: DEWAS
[295/652] Already exists: DHAR
[296/652] Already exists: DINDORI
[297/652] Already exists: GUNA
[298/652] Already exists: GWALIOR
[299/652] Already exists: HARDA
[300/652] Already exists: HOSHANGABAD
[301/652] Already exists: INDORE
[302/652] Already exists: JABALPUR
[303/652] Already exists: JHABUA
[304/652] Already exists: KATNI
[305/652] Already exists: KHANDWA
[306/652] Already exists: KHARGONE
[307/652] Already exists: MANDLA
[308/652] Already exists: MANDSAUR
[309/652] Already exists: MORENA
[310/652] Already exists: NARSINGHPUR
[311/652] Already exists: NEEMUCH
[312/652] Already exists: PANNA
[313/652] Already exists: RAISEN
[314/652] Already exists: RAJGARH
[315/652] Already exists: RATLAM
[316/652] Already exists: REWA
[317/652] Already exists: SAGAR
[318/652] Already exists: SATNA
[319/652] Already exists: SEHORE
[320/652] Already exists: SEONI
[321/652] Already exists: SHAHDOL
[322/652] Already exists: SHAJAPUR
[323/652] Already exists: SHEOPUR
[324/652] Already exists: SHIVPURI
[325/652] Already exists: SIDHI
[326/652] Already exists: SINGRAULI
[327/652] Already exists: TIKAMGARH
[328/652] Already exists: UJJAIN
[329/652] Already exists: UMARIA
[330/652] Already exists: VIDISHA
[331/652] Already exists: AHMEDNAGAR
[332/652] Already exists: AKOLA
[333/652] Already exists: AMRAVATI
[334/652] Already exists: AURANGABAD
[335/652] Already exists: BEED
[336/652] Already exists: BHANDARA
[337/652] Already exists: BULDHANA
[338/652] Already exists: CHANDRAPUR
[339/652] Already exists: DHULE
[340/652] Already exists: GADCHIROLI
[341/652] Already exists: GONDIA
[342/652] Already exists: HINGOLI
[343/652] Already exists: JALGAON
[344/652] Already exists: JALNA
[345/652] Already exists: KOLHAPUR
[346/652] Already exists: LATUR
[347/652] Already exists: MUMBAI
[348/652] Already exists: NAGPUR
[349/652] Already exists: NANDED
[350/652] Already exists: NANDURBAR
[351/652] Already exists: NASHIK
[352/652] Already exists: OSMANABAD
[353/652] Already exists: PALGHAR
[354/652] Already exists: PARBHANI
[355/652] Already exists: PUNE
[356/652] Already exists: RAIGAD
[357/652] Already exists: RATNAGIRI
[358/652] Already exists: SANGLI
[359/652] Already exists: SATARA
[360/652] Already exists: SINDHUDURG
[361/652] Already exists: SOLAPUR
[362/652] Already exists: THANE
[363/652] Already exists: WARDHA
[364/652] Already exists: WASHIM
[365/652] Already exists: YAVATMAL
[366/652] Already exists: BISHNUPUR
[367/652] Already exists: CHANDEL
[368/652] Already exists: CHURACHANDPUR
[369/652] Already exists: IMPHAL EAST
[370/652] Already exists: IMPHAL WEST
[371/652] Already exists: SENAPATI
[372/652] Already exists: TAMENGLONG
[373/652] Already exists: THOUBAL
[374/652] Already exists: UKHRUL
[375/652] Already exists: EAST GARO HILLS
[376/652] Already exists: EAST JAINTIA HILLS
[377/652] Already exists: EAST KHASI HILLS
[378/652] Already exists: NORTH GARO HILLS
[379/652] Already exists: RI BHOI
[380/652] Already exists: SOUTH GARO HILLS
[381/652] Already exists: SOUTH WEST GARO HILLS
[382/652] Already exists: SOUTH WEST KHASI HILLS
[383/652] Already exists: WEST GARO HILLS
[384/652] Already exists: WEST JAINTIA HILLS
[385/652] Already exists: WEST KHASI HILLS
[386/652] Already exists: AIZAWL
[387/652] Already exists: CHAMPHAI
[388/652] Already exists: KOLASIB
[389/652] Already exists: LAWNGTLAI
[390/652] Already exists: LUNGLEI
[391/652] Already exists: MAMIT
[392/652] Already exists: SAIHA
[393/652] Already exists: SERCHHIP
[394/652] Already exists: DIMAPUR
[395/652] Already exists: KIPHIRE
[396/652] Already exists: KOHIMA
[397/652] Already exists: LONGLENG
[398/652] Already exists: MOKOKCHUNG
[399/652] Already exists: MON
[400/652] Already exists: PEREN
[401/652] Already exists: PHEK
[402/652] Already exists: TUENSANG
[403/652] Already exists: WOKHA
[404/652] Already exists: ZUNHEBOTO
[405/652] Already exists: ANUGUL
[406/652] Already exists: BALANGIR
[407/652] Already exists: BALESHWAR
[408/652] Already exists: BARGARH
[409/652] Already exists: BHADRAK
[410/652] Already exists: BOUDH
[411/652] Already exists: CUTTACK
[412/652] Already exists: DEOGARH
[413/652] Already exists: DHENKANAL
[414/652] Already exists: GAJAPATI
[415/652] Already exists: GANJAM
[416/652] Already exists: JAGATSINGHAPUR
[417/652] Already exists: JAJAPUR
[418/652] Already exists: JHARSUGUDA
[419/652] Already exists: KALAHANDI
[420/652] Already exists: KANDHAMAL
[421/652] Already exists: KENDRAPARA
[422/652] Already exists: KENDUJHAR
[423/652] Already exists: KHORDHA
[424/652] Already exists: KORAPUT
[425/652] Already exists: MALKANGIRI
[426/652] Already exists: MAYURBHANJ
[427/652] Already exists: NABARANGPUR
[428/652] Already exists: NAYAGARH
[429/652] Already exists: NUAPADA
[430/652] Already exists: PURI
[431/652] Already exists: RAYAGADA
[432/652] Already exists: SAMBALPUR
[433/652] Already exists: SONEPUR
[434/652] Already exists: SUNDARGARH
[435/652] Already exists: KARAIKAL
[436/652] Already exists: MAHE
[437/652] Already exists: PONDICHERRY
[438/652] Already exists: YANAM
[439/652] Already exists: AMRITSAR
[440/652] Already exists: BARNALA
[441/652] Already exists: BATHINDA
[442/652] Already exists: FARIDKOT
[443/652] Already exists: FATEHGARH SAHIB
[444/652] Already exists: FAZILKA
[445/652] Already exists: FIROZEPUR
[446/652] Already exists: GURDASPUR
[447/652] Already exists: HOSHIARPUR
[448/652] Already exists: JALANDHAR
[449/652] Already exists: KAPURTHALA
[450/652] Already exists: LUDHIANA
[451/652] Already exists: MANSA
[452/652] Already exists: MOGA
[453/652] Already exists: MUKTSAR
[454/652] Already exists: NAWANSHAHR
[455/652] Already exists: PATHANKOT
[456/652] Already exists: PATIALA
[457/652] Already exists: RUPNAGAR
[458/652] Already exists: S.A.S NAGAR
[459/652] Already exists: SANGRUR
[460/652] Already exists: TARN TARAN
[461/652] Already exists: AJMER
[462/652] Already exists: ALWAR
[463/652] Already exists: BANSWARA
[464/652] Already exists: BARAN
[465/652] Already exists: BARMER
[466/652] Already exists: BHARATPUR
[467/652] Already exists: BHILWARA
[468/652] Already exists: BIKANER
[469/652] Already exists: BUNDI
[470/652] Already exists: CHITTORGARH
[471/652] Already exists: CHURU
[472/652] Already exists: DAUSA
[473/652] Already exists: DHOLPUR
[474/652] Already exists: DUNGARPUR
[475/652] Already exists: GANGANAGAR
[476/652] Already exists: HANUMANGARH
[477/652] Already exists: JAIPUR
[478/652] Already exists: JAISALMER
[479/652] Already exists: JALORE
[480/652] Already exists: JHALAWAR
[481/652] Already exists: JHUNJHUNU
[482/652] Already exists: JODHPUR
[483/652] Already exists: KARAULI
[484/652] Already exists: KOTA
[485/652] Already exists: NAGAUR
[486/652] Already exists: PALI
[487/652] Already exists: PRATAPGARH
[488/652] Already exists: RAJSAMAND
[489/652] Already exists: SAWAI MADHOPUR
[490/652] Already exists: SIKAR
[491/652] Already exists: SIROHI
[492/652] Already exists: TONK
[493/652] Already exists: UDAIPUR
[494/652] Already exists: EAST DISTRICT
[495/652] Already exists: NORTH DISTRICT
[496/652] Already exists: SOUTH DISTRICT
[497/652] Already exists: WEST DISTRICT
[498/652] Already exists: ARIYALUR
[499/652] Already exists: COIMBATORE
[500/652] Already exists: CUDDALORE
[501/652] Already exists: DHARMAPURI
[502/652] Already exists: DINDIGUL
[503/652] Already exists: ERODE
[504/652] Already exists: KANCHIPURAM
[505/652] Already exists: KANNIYAKUMARI
[506/652] Already exists: KARUR
[507/652] Already exists: KRISHNAGIRI
[508/652] Already exists: MADURAI
[509/652] Already exists: NAGAPATTINAM
[510/652] Already exists: NAMAKKAL
[511/652] Already exists: PERAMBALUR
[512/652] Already exists: PUDUKKOTTAI
[513/652] Already exists: RAMANATHAPURAM
[514/652] Already exists: SALEM
[515/652] Already exists: SIVAGANGA
[516/652] Already exists: THANJAVUR
[517/652] Already exists: THE NILGIRIS
[518/652] Already exists: THENI
[519/652] Already exists: THIRUVALLUR
[520/652] Already exists: THIRUVARUR
[521/652] Already exists: TIRUCHIRAPPALLI
[522/652] Already exists: TIRUNELVELI
[523/652] Already exists: TIRUPPUR
[524/652] Already exists: TIRUVANNAMALAI
[525/652] Already exists: TUTICORIN
[526/652] Already exists: VELLORE
[527/652] Already exists: VILLUPURAM
[528/652] Already exists: VIRUDHUNAGAR
[529/652] Already exists: ADILABAD
[530/652] Already exists: HYDERABAD
[531/652] Already exists: KARIMNAGAR
[532/652] Already exists: KHAMMAM
[533/652] Already exists: MAHBUBNAGAR
[534/652] Already exists: MEDAK
[535/652] Already exists: NALGONDA
[536/652] Already exists: NIZAMABAD
[537/652] Already exists: RANGAREDDI
[538/652] Already exists: WARANGAL
[539/652] Already exists: DHALAI
[540/652] Already exists: GOMATI
[541/652] Already exists: KHOWAI
[542/652] Already exists: NORTH TRIPURA
[543/652] Already exists: SEPAHIJALA
[544/652] Already exists: SOUTH TRIPURA
[545/652] Already exists: UNAKOTI
[546/652] Already exists: WEST TRIPURA
[547/652] Already exists: AGRA
[548/652] Already exists: ALIGARH
[549/652] Already exists: ALLAHABAD
[550/652] Already exists: AMBEDKAR NAGAR
[551/652] Already exists: AMETHI
[552/652] Already exists: AMROHA
[553/652] Already exists: AURAIYA
[554/652] Already exists: AZAMGARH
[555/652] Already exists: BAGHPAT
[556/652] Already exists: BAHRAICH
[557/652] Already exists: BALLIA
[558/652] Already exists: BALRAMPUR
[559/652] Already exists: BANDA
[560/652] Already exists: BARABANKI
[561/652] Already exists: BAREILLY
[562/652] Already exists: BASTI
[563/652] Already exists: BIJNOR
[564/652] Already exists: BUDAUN
[565/652] Already exists: BULANDSHAHR
[566/652] Already exists: CHANDAULI
[567/652] Already exists: CHITRAKOOT
[568/652] Already exists: DEORIA
[569/652] Already exists: ETAH
[570/652] Already exists: ETAWAH
[571/652] Already exists: FAIZABAD

In [180]:
weather_df["state_name"] = district["state_name"]
weather_df["district_name"] = district["district_name"]

In [181]:
weather_files = list(
    OUTPUT_DIR.glob("*.csv")
)

print(
    "Weather files created:",
    len(weather_files)
)

Weather files created: 652

In [182]:
parameters = data["properties"]["parameter"]

weather_test = pd.DataFrame(parameters)

weather_test.index.name = "date"
weather_test.reset_index(inplace=True)

print("Shape:", weather_test.shape)
print("\nColumns:")
print(weather_test.columns.tolist())

print("\nFirst 5 rows:")
print(weather_test.head())

Shape: (8766, 6)

Columns:
['date', 'T2M', 'PRECTOTCORR', 'RH2M', 'WS2M', 'ALLSKY_SFC_SW_DWN']

First 5 rows:
       date    T2M  PRECTOTCORR   RH2M  WS2M  ALLSKY_SFC_SW_DWN
0  19970101  26.22         0.17  71.52  5.34              19.07
1  19970102  26.58         0.02  70.50  5.16              20.84
2  19970103  26.81         0.00  67.64  4.48              21.26
3  19970104  26.82         0.02  71.07  4.80              18.26
4  19970105  26.37         0.06  73.69  5.18              16.90

In [183]:
from pathlib import Path

OUTPUT_DIR = Path("../../data/weather")

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("Weather folder:", OUTPUT_DIR.resolve())

Weather folder: D:\VS CODE SAVES\NTCC\KrishKalp\KrishiKalp-Smart-Crop-Recommendation-website-\data\weather

In [184]:
url = (
    "https://power.larc.nasa.gov/api/temporal/daily/point"
    f"?parameters=T2M,PRECTOTCORR,RH2M,WS2M,ALLSKY_SFC_SW_DWN"
    f"&community=AG"
    f"&latitude={lat}"
    f"&longitude={lon}"
    f"&start=19970101"
    f"&end=20201231"
    f"&format=JSON"
)

response = requests.get(url, timeout=60)

print("Status Code:", response.status_code)

Status Code: 200

In [185]:
data = response.json()

print(data.keys())

dict_keys(['type', 'geometry', 'properties', 'header', 'messages', 'parameters', 'times'])

In [186]:
print(data["properties"].keys())

dict_keys(['parameter'])

In [187]:
print(data["properties"]["parameter"].keys())

dict_keys(['T2M', 'PRECTOTCORR', 'RH2M', 'WS2M', 'ALLSKY_SFC_SW_DWN'])

In [188]:
t2m = data["properties"]["parameter"]["T2M"]

print(type(t2m))
print("Number of days:", len(t2m))

# Show first 5 entries
list(t2m.items())[:5]

<class 'dict'>
Number of days: 8766

[('19970101', 26.22),
 ('19970102', 26.58),
 ('19970103', 26.81),
 ('19970104', 26.82),
 ('19970105', 26.37)]

In [189]:
t2m_df = (
    pd.DataFrame(
        t2m.items(),
        columns=["date", "temperature"]
    )
)

t2m_df.head()

       date  temperature
0  19970101        26.22
1  19970102        26.58
2  19970103        26.81
3  19970104        26.82
4  19970105        26.37

In [190]:
weather_df = pd.DataFrame({
    "date": list(data["properties"]["parameter"]["T2M"].keys()),
    "temperature": list(data["properties"]["parameter"]["T2M"].values()),
    "rainfall": list(data["properties"]["parameter"]["PRECTOTCORR"].values()),
    "humidity": list(data["properties"]["parameter"]["RH2M"].values()),
    "wind_speed": list(data["properties"]["parameter"]["WS2M"].values()),
    "solar_radiation": list(data["properties"]["parameter"]["ALLSKY_SFC_SW_DWN"].values()),
})

weather_df.head()

       date  temperature  rainfall  humidity  wind_speed  solar_radiation
0  19970101        26.22      0.17     71.52        5.34            19.07
1  19970102        26.58      0.02     70.50        5.16            20.84
2  19970103        26.81      0.00     67.64        4.48            21.26
3  19970104        26.82      0.02     71.07        4.80            18.26
4  19970105        26.37      0.06     73.69        5.18            16.90

In [191]:
weather_df["state_name"] = district["state_name"]
weather_df["district_name"] = district["district_name"]

# Reorder columns
weather_df = weather_df[
    [
        "state_name",
        "district_name",
        "date",
        "temperature",
        "rainfall",
        "humidity",
        "wind_speed",
        "solar_radiation"
    ]
]

weather_df.head()

,state_name,district_name,date,temperature,rainfall,humidity,wind_speed,solar_radiation
0,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,19970101,26.22,0.17,71.52,5.34,19.07
1,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,19970102,26.58,0.02,70.50,5.16,20.84
2,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,19970103,26.81,0.00,67.64,4.48,21.26
3,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,19970104,26.82,0.02,71.07,4.80,18.26
4,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,19970105,26.37,0.06,73.69,5.18,16.90

In [192]:
weather_df["date"] = pd.to_datetime(
    weather_df["date"],
    format="%Y%m%d"
)

weather_df["year"] = weather_df["date"].dt.year

weather_df.head()

,state_name,district_name,date,temperature,rainfall,humidity,wind_speed,solar_radiation,year
0,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,1997-01-01,26.22,0.17,71.52,5.34,19.07,1997
1,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,1997-01-02,26.58,0.02,70.50,5.16,20.84,1997
2,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,1997-01-03,26.81,0.00,67.64,4.48,21.26,1997
3,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,1997-01-04,26.82,0.02,71.07,4.80,18.26,1997
4,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,1997-01-05,26.37,0.06,73.69,5.18,16.90,1997

In [193]:
yearly_weather = (
    weather_df.groupby(
        ["state_name", "district_name", "year"],
        as_index=False
    )
    .agg({
        "temperature": "mean",
        "rainfall": "sum",
        "humidity": "mean",
        "wind_speed": "mean",
        "solar_radiation": "mean"
    })
)

yearly_weather.head()

,state_name,district_name,year,temperature,rainfall,humidity,wind_speed,solar_radiation
0,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,1997,27.548849,1440.00,80.644932,4.814548,19.315781
1,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,1998,28.019781,2002.28,81.466137,4.985205,17.853644
2,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,1999,27.460877,2016.93,82.039151,5.304137,18.164493
3,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,2000,27.495109,2096.57,81.762404,5.256749,18.200765
4,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,2001,27.684466,2040.81,81.582603,5.188192,18.138466

In [194]:
print("Shape:", yearly_weather.shape)
print("Years:", yearly_weather["year"].min(), "-", yearly_weather["year"].max())

Shape: (24, 8)
Years: 1997 - 2020

In [195]:
def download_weather(latitude, longitude):
    """
    Download daily weather data (1997-2020)
    from NASA POWER API.
    """

    url = (
        "https://power.larc.nasa.gov/api/temporal/daily/point"
        f"?parameters=T2M,PRECTOTCORR,RH2M,WS2M,ALLSKY_SFC_SW_DWN"
        f"&community=AG"
        f"&latitude={latitude}"
        f"&longitude={longitude}"
        f"&start=19970101"
        f"&end=20201231"
        f"&format=JSON"
    )

    response = requests.get(url, timeout=60)

    response.raise_for_status()

    return response.json()

In [196]:
def parse_weather(data, state_name, district_name):
    """
    Convert NASA POWER JSON to a daily weather DataFrame.
    """

    weather_df = pd.DataFrame({
        "date": list(data["properties"]["parameter"]["T2M"].keys()),
        "temperature": list(data["properties"]["parameter"]["T2M"].values()),
        "rainfall": list(data["properties"]["parameter"]["PRECTOTCORR"].values()),
        "humidity": list(data["properties"]["parameter"]["RH2M"].values()),
        "wind_speed": list(data["properties"]["parameter"]["WS2M"].values()),
        "solar_radiation": list(data["properties"]["parameter"]["ALLSKY_SFC_SW_DWN"].values()),
    })

    weather_df["state_name"] = state_name
    weather_df["district_name"] = district_name

    weather_df["date"] = pd.to_datetime(
        weather_df["date"],
        format="%Y%m%d"
    )

    weather_df["year"] = weather_df["date"].dt.year

    return weather_df

In [197]:
def aggregate_weather(weather_df):
    """
    Aggregate daily weather data into yearly weather statistics.
    """

    yearly_weather = (
        weather_df
        .groupby(
            ["state_name", "district_name", "year"],
            as_index=False
        )
        .agg({
            "temperature": "mean",
            "rainfall": "sum",
            "humidity": "mean",
            "wind_speed": "mean",
            "solar_radiation": "mean"
        })
    )

    return yearly_weather

In [198]:
data = download_weather(lat, lon)

daily_weather = parse_weather(
    data,
    district["state_name"],
    district["district_name"]
)

yearly_weather = aggregate_weather(daily_weather)

print(yearly_weather.shape)

yearly_weather.head()

(24, 8)

,state_name,district_name,year,temperature,rainfall,humidity,wind_speed,solar_radiation
0,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,1997,27.548849,1440.00,80.644932,4.814548,19.315781
1,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,1998,28.019781,2002.28,81.466137,4.985205,17.853644
2,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,1999,27.460877,2016.93,82.039151,5.304137,18.164493
3,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,2000,27.495109,2096.57,81.762404,5.256749,18.200765
4,ANDAMAN AND NICOBAR ISLANDS,NICOBARS,2001,27.684466,2040.81,81.582603,5.188192,18.138466

In [199]:
from pathlib import Path

OUTPUT_DIR = Path("../../data/weather")

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print(OUTPUT_DIR)

..\..\data\weather

In [200]:
all_weather = []

for _, row in weather_districts.head(3).iterrows():

    print(f"Processing: {row['district_name']}")

    data = download_weather(
        row["latitude"],
        row["longitude"]
    )

    daily_weather = parse_weather(
        data,
        row["state_name"],
        row["district_name"]
    )

    yearly_weather = aggregate_weather(daily_weather)

    all_weather.append(yearly_weather)

print("\nCompleted!")

Processing: NICOBARS
Processing: NORTH AND MIDDLE ANDAMAN
Processing: SOUTH ANDAMANS

Completed!

In [201]:
for _, row in weather_districts.iterrows():

    filename = (
        row["state_name"] + "_" + row["district_name"]
    ).replace(" ", "_").replace("/", "_") + ".csv"

    filepath = OUTPUT_DIR / filename

    if filepath.exists():
        print(f"Skipping: {filename}")
        continue

    try:

        print(f"Processing: {row['district_name']}")

        data = download_weather(
            row["Latitude"],
            row["Longitude"]
        )

        daily_weather = parse_weather(
            data,
            row["state_name"],
            row["district_name"]
        )

        yearly_weather = aggregate_weather(daily_weather)

        yearly_weather.to_csv(
            filepath,
            index=False
        )

        print(f"Saved: {filename}")

    except Exception as e:

        print(f"Failed: {filename}")
        print(e)

print("\nAll districts processed!")

Skipping: ANDAMAN_AND_NICOBAR_ISLANDS_NICOBARS.csv
Skipping: ANDAMAN_AND_NICOBAR_ISLANDS_NORTH_AND_MIDDLE_ANDAMAN.csv
Skipping: ANDAMAN_AND_NICOBAR_ISLANDS_SOUTH_ANDAMANS.csv
Skipping: ANDHRA_PRADESH_CHITTOOR.csv
Skipping: ANDHRA_PRADESH_EAST_GODAVARI.csv
Skipping: ANDHRA_PRADESH_GUNTUR.csv
Skipping: ANDHRA_PRADESH_KRISHNA.csv
Skipping: ANDHRA_PRADESH_KURNOOL.csv
Skipping: ANDHRA_PRADESH_PRAKASAM.csv
Skipping: ANDHRA_PRADESH_SRIKAKULAM.csv
Skipping: ANDHRA_PRADESH_VIZIANAGARAM.csv
Skipping: ANDHRA_PRADESH_WEST_GODAVARI.csv
Skipping: ARUNACHAL_PRADESH_ANJAW.csv
Skipping: ARUNACHAL_PRADESH_CHANGLANG.csv
Skipping: ARUNACHAL_PRADESH_DIBANG_VALLEY.csv
Skipping: ARUNACHAL_PRADESH_EAST_KAMENG.csv
Skipping: ARUNACHAL_PRADESH_EAST_SIANG.csv
Skipping: ARUNACHAL_PRADESH_KURUNG_KUMEY.csv
Skipping: ARUNACHAL_PRADESH_LOHIT.csv
Skipping: ARUNACHAL_PRADESH_LONGDING.csv
Skipping: ARUNACHAL_PRADESH_LOWER_DIBANG_VALLEY.csv
Skipping: ARUNACHAL_PRADESH_LOWER_SUBANSIRI.csv
Skipping: ARUNACHAL_PRADESH_NAMSAI.csv
Skipping: ARUNACHAL_PRADESH_PAPUM_PARE.csv
Skipping: ARUNACHAL_PRADESH_TAWANG.csv
Skipping: ARUNACHAL_PRADESH_TIRAP.csv
Skipping: ARUNACHAL_PRADESH_UPPER_SIANG.csv
Skipping: ARUNACHAL_PRADESH_UPPER_SUBANSIRI.csv
Skipping: ARUNACHAL_PRADESH_WEST_KAMENG.csv
Skipping: ARUNACHAL_PRADESH_WEST_SIANG.csv
Skipping: ASSAM_BAKSA.csv
Skipping: ASSAM_BARPETA.csv
Skipping: ASSAM_BONGAIGAON.csv
Skipping: ASSAM_CACHAR.csv
Skipping: ASSAM_CHIRANG.csv
Skipping: ASSAM_DARRANG.csv
Skipping: ASSAM_DHEMAJI.csv
Skipping: ASSAM_DHUBRI.csv
Skipping: ASSAM_DIBRUGARH.csv
Skipping: ASSAM_DIMA_HASAO.csv
Skipping: ASSAM_GOALPARA.csv
Skipping: ASSAM_GOLAGHAT.csv
Skipping: ASSAM_HAILAKANDI.csv
Skipping: ASSAM_JORHAT.csv
Skipping: ASSAM_KAMRUP.csv
Skipping: ASSAM_KAMRUP_METRO.csv
Skipping: ASSAM_KARBI_ANGLONG.csv
Skipping: ASSAM_KOKRAJHAR.csv
Skipping: ASSAM_LAKHIMPUR.csv
Skipping: ASSAM_MARIGAON.csv
Skipping: ASSAM_NAGAON.csv
Skipping: ASSAM_NALBARI.csv
Skipping: ASSAM_SIVASAGAR.csv
Skipping: ASSAM_SONITPUR.csv
Skipping: ASSAM_TINSUKIA.csv
Skipping: ASSAM_UDALGURI.csv
Skipping: BIHAR_ARARIA.csv
Skipping: BIHAR_ARWAL.csv
Skipping: BIHAR_AURANGABAD.csv
Skipping: BIHAR_BANKA.csv
Skipping: BIHAR_BEGUSARAI.csv
Skipping: BIHAR_BHAGALPUR.csv
Skipping: BIHAR_BHOJPUR.csv
Skipping: BIHAR_BUXAR.csv
Skipping: BIHAR_DARBHANGA.csv
Skipping: BIHAR_GAYA.csv
Skipping: BIHAR_GOPALGANJ.csv
Skipping: BIHAR_JAMUI.csv
Skipping: BIHAR_JEHANABAD.csv
Processing: KAIMUR (BHABUA)
Failed: BIHAR_KAIMUR_(BHABUA).csv
'Latitude'
Skipping: BIHAR_KATIHAR.csv
Skipping: BIHAR_KHAGARIA.csv
Skipping: BIHAR_KISHANGANJ.csv
Skipping: BIHAR_LAKHISARAI.csv
Skipping: BIHAR_MADHEPURA.csv
Skipping: BIHAR_MADHUBANI.csv
Skipping: BIHAR_MUNGER.csv
Skipping: BIHAR_MUZAFFARPUR.csv
Skipping: BIHAR_NALANDA.csv
Skipping: BIHAR_NAWADA.csv
Skipping: BIHAR_PASHCHIM_CHAMPARAN.csv
Skipping: BIHAR_PATNA.csv
Skipping: BIHAR_PURBI_CHAMPARAN.csv
Skipping: BIHAR_PURNIA.csv
Skipping: BIHAR_ROHTAS.csv
Skipping: BIHAR_SAHARSA.csv
Skipping: BIHAR_SAMASTIPUR.csv
Skipping: BIHAR_SARAN.csv
Skipping: BIHAR_SHEIKHPURA.csv
Skipping: BIHAR_SHEOHAR.csv
Skipping: BIHAR_SITAMARHI.csv
Skipping: BIHAR_SIWAN.csv
Skipping: BIHAR_SUPAUL.csv
Skipping: BIHAR_VAISHALI.csv
Skipping: CHHATTISGARH_BALOD.csv
Skipping: CHHATTISGARH_BALRAMPUR.csv
Skipping: CHHATTISGARH_BASTAR.csv
Skipping: CHHATTISGARH_BEMETARA.csv
Skipping: CHHATTISGARH_BIJAPUR.csv
Skipping: CHHATTISGARH_BILASPUR.csv
Skipping: CHHATTISGARH_DHAMTARI.csv
Skipping: CHHATTISGARH_DURG.csv
Skipping: CHHATTISGARH_GARIYABAND.csv
Skipping: CHHATTISGARH_JANJGIR-CHAMPA.csv
Skipping: CHHATTISGARH_JASHPUR.csv
Skipping: CHHATTISGARH_KONDAGAON.csv
Skipping: CHHATTISGARH_KORBA.csv
Skipping: CHHATTISGARH_KOREA.csv
Skipping: CHHATTISGARH_MAHASAMUND.csv
Skipping: CHHATTISGARH_MUNGELI.csv
Skipping: CHHATTISGARH_NARAYANPUR.csv
Skipping: CHHATTISGARH_RAIGARH.csv
Skipping: CHHATTISGARH_RAIPUR.csv
Skipping: CHHATTISGARH_RAJNANDGAON.csv
Skipping: CHHATTISGARH_SUKMA.csv
Skipping: CHHATTISGARH_SURAJPUR.csv
Skipping: CHHATTISGARH_SURGUJA.csv
Skipping: GOA_NORTH_GOA.csv
Skipping: GOA_SOUTH_GOA.csv
Skipping: GUJARAT_AMRELI.csv
Skipping: GUJARAT_ANAND.csv
Skipping: GUJARAT_BANAS_KANTHA.csv
Skipping: GUJARAT_BHARUCH.csv
Skipping: GUJARAT_BHAVNAGAR.csv
Skipping: GUJARAT_GANDHINAGAR.csv
Skipping: GUJARAT_JAMNAGAR.csv
Skipping: GUJARAT_JUNAGADH.csv
Skipping: GUJARAT_KACHCHH.csv
Skipping: GUJARAT_KHEDA.csv
Skipping: GUJARAT_MAHESANA.csv
Skipping: GUJARAT_NARMADA.csv
Skipping: GUJARAT_NAVSARI.csv
Skipping: GUJARAT_PANCH_MAHALS.csv
Skipping: GUJARAT_PATAN.csv
Skipping: GUJARAT_PORBANDAR.csv
Skipping: GUJARAT_RAJKOT.csv
Skipping: GUJARAT_SABAR_KANTHA.csv
Skipping: GUJARAT_SURAT.csv
Skipping: GUJARAT_SURENDRANAGAR.csv
Skipping: GUJARAT_TAPI.csv
Skipping: GUJARAT_VADODARA.csv
Skipping: GUJARAT_VALSAD.csv
Skipping: HARYANA_AMBALA.csv
Skipping: HARYANA_BHIWANI.csv
Skipping: HARYANA_FARIDABAD.csv
Skipping: HARYANA_FATEHABAD.csv
Skipping: HARYANA_HISAR.csv
Skipping: HARYANA_JHAJJAR.csv
Skipping: HARYANA_JIND.csv
Skipping: HARYANA_KAITHAL.csv
Skipping: HARYANA_KARNAL.csv
Skipping: HARYANA_KURUKSHETRA.csv
Skipping: HARYANA_MAHENDRAGARH.csv
Skipping: HARYANA_PALWAL.csv
Skipping: HARYANA_PANCHKULA.csv
Skipping: HARYANA_PANIPAT.csv
Skipping: HARYANA_REWARI.csv
Skipping: HARYANA_ROHTAK.csv
Skipping: HARYANA_SIRSA.csv
Skipping: HARYANA_SONIPAT.csv
Skipping: HARYANA_YAMUNANAGAR.csv
Skipping: HIMACHAL_PRADESH_BILASPUR.csv
Skipping: HIMACHAL_PRADESH_CHAMBA.csv
Skipping: HIMACHAL_PRADESH_HAMIRPUR.csv
Skipping: HIMACHAL_PRADESH_KANGRA.csv
Skipping: HIMACHAL_PRADESH_KINNAUR.csv
Skipping: HIMACHAL_PRADESH_KULLU.csv
Skipping: HIMACHAL_PRADESH_MANDI.csv
Skipping: HIMACHAL_PRADESH_SHIMLA.csv
Skipping: HIMACHAL_PRADESH_SIRMAUR.csv
Skipping: HIMACHAL_PRADESH_SOLAN.csv
Skipping: HIMACHAL_PRADESH_UNA.csv
Skipping: JAMMU_AND_KASHMIR_ANANTNAG.csv
Skipping: JAMMU_AND_KASHMIR_BANDIPORA.csv
Skipping: JAMMU_AND_KASHMIR_BARAMULLA.csv
Skipping: JAMMU_AND_KASHMIR_DODA.csv
Skipping: JAMMU_AND_KASHMIR_GANDERBAL.csv
Skipping: JAMMU_AND_KASHMIR_JAMMU.csv
Skipping: JAMMU_AND_KASHMIR_KARGIL.csv
Skipping: JAMMU_AND_KASHMIR_KATHUA.csv
Skipping: JAMMU_AND_KASHMIR_KISHTWAR.csv
Skipping: JAMMU_AND_KASHMIR_KULGAM.csv
Skipping: JAMMU_AND_KASHMIR_KUPWARA.csv
Skipping: JAMMU_AND_KASHMIR_LEH_LADAKH.csv
Skipping: JAMMU_AND_KASHMIR_POONCH.csv
Skipping: JAMMU_AND_KASHMIR_PULWAMA.csv
Skipping: JAMMU_AND_KASHMIR_RAMBAN.csv
Skipping: JAMMU_AND_KASHMIR_REASI.csv
Skipping: JAMMU_AND_KASHMIR_SAMBA.csv
Skipping: JAMMU_AND_KASHMIR_SHOPIAN.csv
Skipping: JAMMU_AND_KASHMIR_SRINAGAR.csv
Skipping: JAMMU_AND_KASHMIR_UDHAMPUR.csv
Skipping: JHARKHAND_BOKARO.csv
Skipping: JHARKHAND_CHATRA.csv
Skipping: JHARKHAND_DEOGHAR.csv
Skipping: JHARKHAND_DHANBAD.csv
Skipping: JHARKHAND_DUMKA.csv
Skipping: JHARKHAND_EAST_SINGHBUM.csv
Skipping: JHARKHAND_GARHWA.csv
Skipping: JHARKHAND_GIRIDIH.csv
Skipping: JHARKHAND_GODDA.csv
Skipping: JHARKHAND_GUMLA.csv
Skipping: JHARKHAND_HAZARIBAGH.csv
Skipping: JHARKHAND_JAMTARA.csv
Skipping: JHARKHAND_KHUNTI.csv
Skipping: JHARKHAND_KODERMA.csv
Skipping: JHARKHAND_LATEHAR.csv
Skipping: JHARKHAND_LOHARDAGA.csv
Skipping: JHARKHAND_PAKUR.csv
Skipping: JHARKHAND_PALAMU.csv
Skipping: JHARKHAND_RAMGARH.csv
Skipping: JHARKHAND_RANCHI.csv
Skipping: JHARKHAND_SAHEBGANJ.csv
Skipping: JHARKHAND_SARAIKELA_KHARSAWAN.csv
Skipping: JHARKHAND_SIMDEGA.csv
Skipping: JHARKHAND_WEST_SINGHBHUM.csv
Skipping: KARNATAKA_BENGALURU_URBAN.csv
Skipping: KARNATAKA_BIDAR.csv
Skipping: KARNATAKA_BIJAPUR.csv
Skipping: KARNATAKA_CHAMARAJANAGAR.csv
Skipping: KARNATAKA_CHITRADURGA.csv
Skipping: KARNATAKA_DHARWAD.csv
Skipping: KARNATAKA_GADAG.csv
Skipping: KARNATAKA_HASSAN.csv
Skipping: KARNATAKA_HAVERI.csv
Skipping: KARNATAKA_KODAGU.csv
Skipping: KARNATAKA_KOLAR.csv
Skipping: KARNATAKA_KOPPAL.csv
Skipping: KARNATAKA_MANDYA.csv
Skipping: KARNATAKA_RAICHUR.csv
Skipping: KARNATAKA_UDUPI.csv
Skipping: KARNATAKA_YADGIR.csv
Skipping: KERALA_ALAPPUZHA.csv
Skipping: KERALA_ERNAKULAM.csv
Skipping: KERALA_IDUKKI.csv
Skipping: KERALA_KANNUR.csv
Skipping: KERALA_KASARAGOD.csv
Skipping: KERALA_KOLLAM.csv
Skipping: KERALA_KOTTAYAM.csv
Skipping: KERALA_KOZHIKODE.csv
Skipping: KERALA_MALAPPURAM.csv
Skipping: KERALA_PALAKKAD.csv
Skipping: KERALA_PATHANAMTHITTA.csv
Skipping: KERALA_THIRUVANANTHAPURAM.csv
Skipping: KERALA_THRISSUR.csv
Skipping: KERALA_WAYANAD.csv
Skipping: MADHYA_PRADESH_ALIRAJPUR.csv
Skipping: MADHYA_PRADESH_ANUPPUR.csv
Skipping: MADHYA_PRADESH_ASHOKNAGAR.csv
Skipping: MADHYA_PRADESH_BALAGHAT.csv
Skipping: MADHYA_PRADESH_BARWANI.csv
Skipping: MADHYA_PRADESH_BETUL.csv
Skipping: MADHYA_PRADESH_BHIND.csv
Skipping: MADHYA_PRADESH_BHOPAL.csv
Skipping: MADHYA_PRADESH_BURHANPUR.csv
Skipping: MADHYA_PRADESH_CHHATARPUR.csv
Skipping: MADHYA_PRADESH_CHHINDWARA.csv
Skipping: MADHYA_PRADESH_DAMOH.csv
Skipping: MADHYA_PRADESH_DATIA.csv
Skipping: MADHYA_PRADESH_DEWAS.csv
Skipping: MADHYA_PRADESH_DHAR.csv
Skipping: MADHYA_PRADESH_DINDORI.csv
Skipping: MADHYA_PRADESH_GUNA.csv
Skipping: MADHYA_PRADESH_GWALIOR.csv
Skipping: MADHYA_PRADESH_HARDA.csv
Skipping: MADHYA_PRADESH_INDORE.csv
Skipping: MADHYA_PRADESH_JABALPUR.csv
Skipping: MADHYA_PRADESH_JHABUA.csv
Skipping: MADHYA_PRADESH_KATNI.csv
Skipping: MADHYA_PRADESH_MANDLA.csv
Skipping: MADHYA_PRADESH_MANDSAUR.csv
Skipping: MADHYA_PRADESH_MORENA.csv
Skipping: MADHYA_PRADESH_NEEMUCH.csv
Skipping: MADHYA_PRADESH_PANNA.csv
Skipping: MADHYA_PRADESH_RAISEN.csv
Skipping: MADHYA_PRADESH_RAJGARH.csv
Skipping: MADHYA_PRADESH_RATLAM.csv
Skipping: MADHYA_PRADESH_REWA.csv
Skipping: MADHYA_PRADESH_SAGAR.csv
Skipping: MADHYA_PRADESH_SATNA.csv
Skipping: MADHYA_PRADESH_SEHORE.csv
Skipping: MADHYA_PRADESH_SEONI.csv
Skipping: MADHYA_PRADESH_SHAHDOL.csv
Skipping: MADHYA_PRADESH_SHAJAPUR.csv
Skipping: MADHYA_PRADESH_SHEOPUR.csv
Skipping: MADHYA_PRADESH_SHIVPURI.csv
Skipping: MADHYA_PRADESH_SIDHI.csv
Skipping: MADHYA_PRADESH_SINGRAULI.csv
Skipping: MADHYA_PRADESH_TIKAMGARH.csv
Skipping: MADHYA_PRADESH_UJJAIN.csv
Skipping: MADHYA_PRADESH_UMARIA.csv
Skipping: MADHYA_PRADESH_VIDISHA.csv
Skipping: MAHARASHTRA_AKOLA.csv
Skipping: MAHARASHTRA_AMRAVATI.csv
Skipping: MAHARASHTRA_AURANGABAD.csv
Skipping: MAHARASHTRA_BEED.csv
Skipping: MAHARASHTRA_BHANDARA.csv
Skipping: MAHARASHTRA_BULDHANA.csv
Skipping: MAHARASHTRA_CHANDRAPUR.csv
Skipping: MAHARASHTRA_DHULE.csv
Skipping: MAHARASHTRA_GADCHIROLI.csv
Skipping: MAHARASHTRA_GONDIA.csv
Skipping: MAHARASHTRA_HINGOLI.csv
Skipping: MAHARASHTRA_JALGAON.csv
Skipping: MAHARASHTRA_JALNA.csv
Skipping: MAHARASHTRA_KOLHAPUR.csv
Skipping: MAHARASHTRA_LATUR.csv
Skipping: MAHARASHTRA_NAGPUR.csv
Skipping: MAHARASHTRA_NANDED.csv
Skipping: MAHARASHTRA_NANDURBAR.csv
Skipping: MAHARASHTRA_NASHIK.csv
Skipping: MAHARASHTRA_PALGHAR.csv
Skipping: MAHARASHTRA_PARBHANI.csv
Skipping: MAHARASHTRA_PUNE.csv
Skipping: MAHARASHTRA_RAIGAD.csv
Skipping: MAHARASHTRA_RATNAGIRI.csv
Skipping: MAHARASHTRA_SANGLI.csv
Skipping: MAHARASHTRA_SATARA.csv
Skipping: MAHARASHTRA_SINDHUDURG.csv
Skipping: MAHARASHTRA_SOLAPUR.csv
Skipping: MAHARASHTRA_THANE.csv
Skipping: MAHARASHTRA_WARDHA.csv
Skipping: MAHARASHTRA_WASHIM.csv
Skipping: MAHARASHTRA_YAVATMAL.csv
Skipping: MANIPUR_CHURACHANDPUR.csv
Skipping: MEGHALAYA_EAST_GARO_HILLS.csv
Skipping: MEGHALAYA_EAST_JAINTIA_HILLS.csv
Skipping: MEGHALAYA_EAST_KHASI_HILLS.csv
Skipping: MEGHALAYA_NORTH_GARO_HILLS.csv
Skipping: MEGHALAYA_RI_BHOI.csv
Skipping: MEGHALAYA_SOUTH_GARO_HILLS.csv
Skipping: MEGHALAYA_SOUTH_WEST_GARO_HILLS.csv
Skipping: MEGHALAYA_SOUTH_WEST_KHASI_HILLS.csv
Skipping: MEGHALAYA_WEST_GARO_HILLS.csv
Skipping: MEGHALAYA_WEST_JAINTIA_HILLS.csv
Skipping: MEGHALAYA_WEST_KHASI_HILLS.csv
Skipping: MIZORAM_AIZAWL.csv
Skipping: MIZORAM_CHAMPHAI.csv
Skipping: MIZORAM_KOLASIB.csv
Skipping: MIZORAM_LAWNGTLAI.csv
Skipping: MIZORAM_LUNGLEI.csv
Skipping: MIZORAM_MAMIT.csv
Skipping: MIZORAM_SERCHHIP.csv
Skipping: NAGALAND_DIMAPUR.csv
Skipping: NAGALAND_KIPHIRE.csv
Skipping: NAGALAND_KOHIMA.csv
Skipping: NAGALAND_LONGLENG.csv
Skipping: NAGALAND_MOKOKCHUNG.csv
Skipping: NAGALAND_MON.csv
Skipping: NAGALAND_PEREN.csv
Skipping: NAGALAND_PHEK.csv
Skipping: NAGALAND_TUENSANG.csv
Skipping: NAGALAND_WOKHA.csv
Skipping: NAGALAND_ZUNHEBOTO.csv
Skipping: ODISHA_BALANGIR.csv
Skipping: ODISHA_BALESHWAR.csv
Skipping: ODISHA_BARGARH.csv
Skipping: ODISHA_BHADRAK.csv
Skipping: ODISHA_BOUDH.csv
Skipping: ODISHA_CUTTACK.csv
Skipping: ODISHA_DEOGARH.csv
Skipping: ODISHA_DHENKANAL.csv
Skipping: ODISHA_GAJAPATI.csv
Skipping: ODISHA_GANJAM.csv
Skipping: ODISHA_JAGATSINGHAPUR.csv
Skipping: ODISHA_JHARSUGUDA.csv
Skipping: ODISHA_KALAHANDI.csv
Skipping: ODISHA_KANDHAMAL.csv
Skipping: ODISHA_KENDRAPARA.csv
Skipping: ODISHA_KENDUJHAR.csv
Skipping: ODISHA_KHORDHA.csv
Skipping: ODISHA_KORAPUT.csv
Skipping: ODISHA_MALKANGIRI.csv
Skipping: ODISHA_MAYURBHANJ.csv
Skipping: ODISHA_NABARANGPUR.csv
Skipping: ODISHA_NAYAGARH.csv
Skipping: ODISHA_NUAPADA.csv
Skipping: ODISHA_PURI.csv
Skipping: ODISHA_RAYAGADA.csv
Skipping: ODISHA_SAMBALPUR.csv
Skipping: ODISHA_SONEPUR.csv
Skipping: ODISHA_SUNDARGARH.csv
Skipping: PUDUCHERRY_KARAIKAL.csv
Skipping: PUNJAB_AMRITSAR.csv
Skipping: PUNJAB_BARNALA.csv
Skipping: PUNJAB_BATHINDA.csv
Skipping: PUNJAB_FARIDKOT.csv
Skipping: PUNJAB_FATEHGARH_SAHIB.csv
Skipping: PUNJAB_FAZILKA.csv
Skipping: PUNJAB_GURDASPUR.csv
Skipping: PUNJAB_HOSHIARPUR.csv
Skipping: PUNJAB_JALANDHAR.csv
Skipping: PUNJAB_KAPURTHALA.csv
Skipping: PUNJAB_LUDHIANA.csv
Skipping: PUNJAB_MANSA.csv
Skipping: PUNJAB_MOGA.csv
Skipping: PUNJAB_PATHANKOT.csv
Skipping: PUNJAB_PATIALA.csv
Skipping: PUNJAB_RUPNAGAR.csv
Skipping: PUNJAB_S.A.S_NAGAR.csv
Skipping: PUNJAB_SANGRUR.csv
Skipping: PUNJAB_TARN_TARAN.csv
Skipping: RAJASTHAN_AJMER.csv
Skipping: RAJASTHAN_ALWAR.csv
Skipping: RAJASTHAN_BANSWARA.csv
Skipping: RAJASTHAN_BARAN.csv
Skipping: RAJASTHAN_BARMER.csv
Skipping: RAJASTHAN_BHARATPUR.csv
Skipping: RAJASTHAN_BHILWARA.csv
Skipping: RAJASTHAN_BIKANER.csv
Skipping: RAJASTHAN_BUNDI.csv
Skipping: RAJASTHAN_CHITTORGARH.csv
Skipping: RAJASTHAN_CHURU.csv
Skipping: RAJASTHAN_DAUSA.csv
Skipping: RAJASTHAN_DHOLPUR.csv
Skipping: RAJASTHAN_DUNGARPUR.csv
Skipping: RAJASTHAN_GANGANAGAR.csv
Skipping: RAJASTHAN_HANUMANGARH.csv
Skipping: RAJASTHAN_JAIPUR.csv
Skipping: RAJASTHAN_JAISALMER.csv
Skipping: RAJASTHAN_JALORE.csv
Skipping: RAJASTHAN_JHALAWAR.csv
Skipping: RAJASTHAN_JHUNJHUNU.csv
Skipping: RAJASTHAN_JODHPUR.csv
Skipping: RAJASTHAN_KARAULI.csv
Skipping: RAJASTHAN_KOTA.csv
Skipping: RAJASTHAN_NAGAUR.csv
Skipping: RAJASTHAN_PALI.csv
Skipping: RAJASTHAN_PRATAPGARH.csv
Skipping: RAJASTHAN_RAJSAMAND.csv
Skipping: RAJASTHAN_SAWAI_MADHOPUR.csv
Skipping: RAJASTHAN_SIKAR.csv
Skipping: RAJASTHAN_SIROHI.csv
Skipping: RAJASTHAN_TONK.csv
Skipping: RAJASTHAN_UDAIPUR.csv
Skipping: TAMIL_NADU_ARIYALUR.csv
Skipping: TAMIL_NADU_COIMBATORE.csv
Skipping: TAMIL_NADU_CUDDALORE.csv
Skipping: TAMIL_NADU_DHARMAPURI.csv
Skipping: TAMIL_NADU_DINDIGUL.csv
Skipping: TAMIL_NADU_ERODE.csv
Skipping: TAMIL_NADU_KANNIYAKUMARI.csv
Skipping: TAMIL_NADU_KARUR.csv
Skipping: TAMIL_NADU_KRISHNAGIRI.csv
Skipping: TAMIL_NADU_MADURAI.csv
Skipping: TAMIL_NADU_NAGAPATTINAM.csv
Skipping: TAMIL_NADU_NAMAKKAL.csv
Skipping: TAMIL_NADU_PERAMBALUR.csv
Skipping: TAMIL_NADU_PUDUKKOTTAI.csv
Skipping: TAMIL_NADU_RAMANATHAPURAM.csv
Skipping: TAMIL_NADU_SALEM.csv
Skipping: TAMIL_NADU_SIVAGANGA.csv
Skipping: TAMIL_NADU_THANJAVUR.csv
Skipping: TAMIL_NADU_THE_NILGIRIS.csv
Skipping: TAMIL_NADU_THENI.csv
Skipping: TAMIL_NADU_THIRUVALLUR.csv
Skipping: TAMIL_NADU_THIRUVARUR.csv
Skipping: TAMIL_NADU_TIRUCHIRAPPALLI.csv
Skipping: TAMIL_NADU_TIRUNELVELI.csv
Skipping: TAMIL_NADU_TIRUPPUR.csv
Skipping: TAMIL_NADU_TIRUVANNAMALAI.csv
Skipping: TAMIL_NADU_VELLORE.csv
Skipping: TAMIL_NADU_VIRUDHUNAGAR.csv
Skipping: TELANGANA_ADILABAD.csv
Skipping: TELANGANA_KARIMNAGAR.csv
Skipping: TELANGANA_KHAMMAM.csv
Skipping: TELANGANA_MEDAK.csv
Skipping: TELANGANA_NALGONDA.csv
Skipping: TELANGANA_NIZAMABAD.csv
Skipping: TELANGANA_WARANGAL.csv
Skipping: TRIPURA_DHALAI.csv
Skipping: TRIPURA_GOMATI.csv
Skipping: TRIPURA_KHOWAI.csv
Skipping: TRIPURA_NORTH_TRIPURA.csv
Skipping: TRIPURA_SEPAHIJALA.csv
Skipping: TRIPURA_SOUTH_TRIPURA.csv
Skipping: TRIPURA_UNAKOTI.csv
Skipping: TRIPURA_WEST_TRIPURA.csv
Skipping: UTTAR_PRADESH_AGRA.csv
Skipping: UTTAR_PRADESH_ALIGARH.csv
Skipping: UTTAR_PRADESH_AMBEDKAR_NAGAR.csv
Skipping: UTTAR_PRADESH_AMETHI.csv
Skipping: UTTAR_PRADESH_AMROHA.csv
Skipping: UTTAR_PRADESH_AURAIYA.csv
Skipping: UTTAR_PRADESH_AZAMGARH.csv
Skipping: UTTAR_PRADESH_BAGHPAT.csv
Skipping: UTTAR_PRADESH_BAHRAICH.csv
Skipping: UTTAR_PRADESH_BALLIA.csv
Skipping: UTTAR_PRADESH_BALRAMPUR.csv
Skipping: UTTAR_PRADESH_BANDA.csv
Skipping: UTTAR_PRADESH_BAREILLY.csv
Skipping: UTTAR_PRADESH_BASTI.csv
Skipping: UTTAR_PRADESH_BIJNOR.csv
Skipping: UTTAR_PRADESH_BUDAUN.csv
Skipping: UTTAR_PRADESH_BULANDSHAHR.csv
Skipping: UTTAR_PRADESH_CHANDAULI.csv
Skipping: UTTAR_PRADESH_CHITRAKOOT.csv
Skipping: UTTAR_PRADESH_DEORIA.csv
Skipping: UTTAR_PRADESH_ETAH.csv
Skipping: UTTAR_PRADESH_ETAWAH.csv
Skipping: UTTAR_PRADESH_FARRUKHABAD.csv
Skipping: UTTAR_PRADESH_FATEHPUR.csv
Skipping: UTTAR_PRADESH_FIROZABAD.csv
Skipping: UTTAR_PRADESH_GAUTAM_BUDDHA_NAGAR.csv
Skipping: UTTAR_PRADESH_GHAZIABAD.csv
Skipping: UTTAR_PRADESH_GHAZIPUR.csv
Skipping: UTTAR_PRADESH_GONDA.csv
Skipping: UTTAR_PRADESH_GORAKHPUR.csv
Skipping: UTTAR_PRADESH_HAMIRPUR.csv
Skipping: UTTAR_PRADESH_HAPUR.csv
Skipping: UTTAR_PRADESH_HARDOI.csv
Skipping: UTTAR_PRADESH_HATHRAS.csv
Skipping: UTTAR_PRADESH_JALAUN.csv
Skipping: UTTAR_PRADESH_JAUNPUR.csv
Skipping: UTTAR_PRADESH_JHANSI.csv
Skipping: UTTAR_PRADESH_KANNAUJ.csv
Skipping: UTTAR_PRADESH_KANPUR_DEHAT.csv
Skipping: UTTAR_PRADESH_KANPUR_NAGAR.csv
Skipping: UTTAR_PRADESH_KASGANJ.csv
Skipping: UTTAR_PRADESH_KAUSHAMBI.csv
Skipping: UTTAR_PRADESH_KHERI.csv
Skipping: UTTAR_PRADESH_LALITPUR.csv
Skipping: UTTAR_PRADESH_LUCKNOW.csv
Skipping: UTTAR_PRADESH_MAHOBA.csv
Skipping: UTTAR_PRADESH_MAINPURI.csv
Skipping: UTTAR_PRADESH_MATHURA.csv
Skipping: UTTAR_PRADESH_MAU.csv
Skipping: UTTAR_PRADESH_MEERUT.csv
Skipping: UTTAR_PRADESH_MIRZAPUR.csv
Skipping: UTTAR_PRADESH_MORADABAD.csv
Skipping: UTTAR_PRADESH_MUZAFFARNAGAR.csv
Skipping: UTTAR_PRADESH_PILIBHIT.csv
Skipping: UTTAR_PRADESH_PRATAPGARH.csv
Skipping: UTTAR_PRADESH_RAE_BARELI.csv
Skipping: UTTAR_PRADESH_RAMPUR.csv
Skipping: UTTAR_PRADESH_SAHARANPUR.csv
Skipping: UTTAR_PRADESH_SAMBHAL.csv
Skipping: UTTAR_PRADESH_SHAHJAHANPUR.csv
Skipping: UTTAR_PRADESH_SHAMLI.csv
Skipping: UTTAR_PRADESH_SITAPUR.csv
Skipping: UTTAR_PRADESH_SONBHADRA.csv
Skipping: UTTAR_PRADESH_SULTANPUR.csv
Skipping: UTTAR_PRADESH_UNNAO.csv
Skipping: UTTAR_PRADESH_VARANASI.csv
Skipping: UTTARAKHAND_ALMORA.csv
Skipping: UTTARAKHAND_BAGESHWAR.csv
Skipping: UTTARAKHAND_CHAMOLI.csv
Skipping: UTTARAKHAND_CHAMPAWAT.csv
Skipping: UTTARAKHAND_DEHRADUN.csv
Skipping: UTTARAKHAND_HARIDWAR.csv
Skipping: UTTARAKHAND_NAINITAL.csv
Skipping: UTTARAKHAND_PAURI_GARHWAL.csv
Skipping: UTTARAKHAND_PITHORAGARH.csv
Skipping: UTTARAKHAND_TEHRI_GARHWAL.csv
Skipping: WEST_BENGAL_BANKURA.csv
Skipping: WEST_BENGAL_BIRBHUM.csv
Skipping: WEST_BENGAL_DARJEELING.csv
Skipping: WEST_BENGAL_HOOGHLY.csv
Skipping: WEST_BENGAL_HOWRAH.csv
Skipping: WEST_BENGAL_JALPAIGURI.csv
Skipping: WEST_BENGAL_MURSHIDABAD.csv
Skipping: WEST_BENGAL_NADIA.csv
Skipping: WEST_BENGAL_PURULIA.csv

All districts processed!

In [202]:
from pathlib import Path
import pandas as pd

weather_files = list(OUTPUT_DIR.glob("*.csv"))

print("Total files:", len(weather_files))

weather_df = pd.concat(
    [pd.read_csv(file) for file in weather_files],
    ignore_index=True
)

print(weather_df.shape)

weather_df.head()

Total files: 652
(5715432, 10)

,date,T2M,PRECTOTCORR,RH2M,WS2M,ALLSKY_SFC_SW_DWN,State_Name,District_Name,latitude,longitude
0,19970101,26.22,0.17,71.52,5.34,19.07,Andaman and Nicobar Islands,NICOBARS,9.15,92.75
1,19970102,26.58,0.02,70.50,5.16,20.84,Andaman and Nicobar Islands,NICOBARS,9.15,92.75
2,19970103,26.81,0.00,67.64,4.48,21.26,Andaman and Nicobar Islands,NICOBARS,9.15,92.75
3,19970104,26.82,0.02,71.07,4.80,18.26,Andaman and Nicobar Islands,NICOBARS,9.15,92.75
4,19970105,26.37,0.06,73.69,5.18,16.90,Andaman and Nicobar Islands,NICOBARS,9.15,92.75

In [203]:
downloaded = {
    f.stem.replace("_", " ")
    for f in weather_files
}

expected = {
    (row["state_name"] + "_" + row["district_name"])
    .replace(" ", "_")
    .replace("/", "_")
    for _, row in weather_districts.iterrows()
}

missing = expected - {f.stem for f in weather_files}

print("Missing districts:", len(missing))

for district in sorted(missing):
    print(district)

Missing districts: 1
BIHAR_KAIMUR_(BHABUA)

In [204]:
print("Unique district names:", weather_districts["district_name"].nunique())
print("Total districts:", len(weather_districts))

duplicates = weather_districts[
    weather_districts.duplicated("district_name", keep=False)
].sort_values("district_name")

duplicates

Unique district names: 557
Total districts: 563

           state_name district_name   latitude  longitude
58              BIHAR    AURANGABAD  24.803320  84.411020
294       MAHARASHTRA    AURANGABAD  19.877263  75.339024
95       CHHATTISGARH     BALRAMPUR  23.628258  83.481092
488     UTTAR PRADESH     BALRAMPUR  27.447699  82.395624
98       CHHATTISGARH       BIJAPUR  18.793568  80.815939
..                ...           ...        ...        ...
161  HIMACHAL PRADESH      BILASPUR  31.338096  76.761163
163  HIMACHAL PRADESH      HAMIRPUR  31.653987  76.540363
508     UTTAR PRADESH      HAMIRPUR  25.750000  80.000000
428         RAJASTHAN    PRATAPGARH  24.023222  74.625028
532     UTTAR PRADESH    PRATAPGARH  25.750000  81.750000

[12 rows x 4 columns]

In [206]:
weather_districts = (
    weather_base[
        ["state_name", "district_name", "latitude", "longitude"]
    ]
    .dropna(subset=["latitude", "longitude"])
    .drop_duplicates()
    .sort_values(["state_name", "district_name"])
    .reset_index(drop=True)
)

# Keep only one coordinate per district
weather_districts = (
    weather_districts
    .drop_duplicates(
        subset=["state_name", "district_name"],
        keep="first"
    )
    .reset_index(drop=True)
)

print("Unique districts:", len(weather_districts))

Unique districts: 563

In [207]:
weather_df.to_csv(
    "../../data/processed/weather_yearly.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!

In [208]:
print(weather_yearly.columns.tolist())
print(weather_yearly.shape)
print(weather_yearly.head())

['State_Name', 'District_Name', 'year', 'temperature', 'rainfall', 'humidity', 'wind_speed', 'solar_radiation']
(15648, 8)
                    State_Name District_Name  year  temperature  rainfall  \
0  Andaman and Nicobar Islands      NICOBARS  1997    27.548849   1440.00
1  Andaman and Nicobar Islands      NICOBARS  1998    28.019781   2002.28
2  Andaman and Nicobar Islands      NICOBARS  1999    27.460877   2016.93
3  Andaman and Nicobar Islands      NICOBARS  2000    27.495109   2096.57
4  Andaman and Nicobar Islands      NICOBARS  2001    27.684466   2040.81

    humidity  wind_speed  solar_radiation
0  80.644932    4.814548        19.315781
1  81.466137    4.985205        17.853644
2  82.039151    5.304137        18.164493
3  81.762404    5.256749        18.200765
4  81.582603    5.188192        18.138466

In [211]:
print("Shape:", weather_yearly.shape)

print(weather_yearly.columns.tolist())

print(weather_yearly.head())

Shape: (15648, 8)
['State_Name', 'District_Name', 'year', 'temperature', 'rainfall', 'humidity', 'wind_speed', 'solar_radiation']
                    State_Name District_Name  year  temperature  rainfall  \
0  Andaman and Nicobar Islands      NICOBARS  1997    27.548849   1440.00
1  Andaman and Nicobar Islands      NICOBARS  1998    28.019781   2002.28
2  Andaman and Nicobar Islands      NICOBARS  1999    27.460877   2016.93
3  Andaman and Nicobar Islands      NICOBARS  2000    27.495109   2096.57
4  Andaman and Nicobar Islands      NICOBARS  2001    27.684466   2040.81

    humidity  wind_speed  solar_radiation
0  80.644932    4.814548        19.315781
1  81.466137    4.985205        17.853644
2  82.039151    5.304137        18.164493
3  81.762404    5.256749        18.200765
4  81.582603    5.188192        18.138466

In [212]:
import pandas as pd

# Load the CURRENT daily weather data
weather_daily = pd.read_csv(
    "../../data/processed/weather_yearly.csv"
)

print("Daily weather shape:", weather_daily.shape)

# Create year
weather_daily["year"] = (
    weather_daily["date"]
    .astype(str)
    .str[:4]
    .astype(int)
)

# Aggregate daily -> yearly
weather_yearly = (
    weather_daily
    .groupby(
        ["State_Name", "District_Name", "year"],
        as_index=False
    )
    .agg(
        temperature=("T2M", "mean"),
        rainfall=("PRECTOTCORR", "sum"),
        humidity=("RH2M", "mean"),
        wind_speed=("WS2M", "mean"),
        solar_radiation=("ALLSKY_SFC_SW_DWN", "mean")
    )
)

print("Yearly weather shape:", weather_yearly.shape)
print(weather_yearly.columns.tolist())
print(weather_yearly.head())

Daily weather shape: (5715432, 10)
Yearly weather shape: (15648, 8)
['State_Name', 'District_Name', 'year', 'temperature', 'rainfall', 'humidity', 'wind_speed', 'solar_radiation']
                    State_Name District_Name  year  temperature  rainfall  \
0  Andaman and Nicobar Islands      NICOBARS  1997    27.548849   1440.00
1  Andaman and Nicobar Islands      NICOBARS  1998    28.019781   2002.28
2  Andaman and Nicobar Islands      NICOBARS  1999    27.460877   2016.93
3  Andaman and Nicobar Islands      NICOBARS  2000    27.495109   2096.57
4  Andaman and Nicobar Islands      NICOBARS  2001    27.684466   2040.81

    humidity  wind_speed  solar_radiation
0  80.644932    4.814548        19.315781
1  81.466137    4.985205        17.853644
2  82.039151    5.304137        18.164493
3  81.762404    5.256749        18.200765
4  81.582603    5.188192        18.138466

In [214]:
print("Shape:", weather_yearly.shape)
print(weather_yearly.columns.tolist())
print(weather_yearly.head())

Shape: (15648, 8)
['State_Name', 'District_Name', 'year', 'temperature', 'rainfall', 'humidity', 'wind_speed', 'solar_radiation']
                    State_Name District_Name  year  temperature  rainfall  \
0  Andaman and Nicobar Islands      NICOBARS  1997    27.548849   1440.00
1  Andaman and Nicobar Islands      NICOBARS  1998    28.019781   2002.28
2  Andaman and Nicobar Islands      NICOBARS  1999    27.460877   2016.93
3  Andaman and Nicobar Islands      NICOBARS  2000    27.495109   2096.57
4  Andaman and Nicobar Islands      NICOBARS  2001    27.684466   2040.81

    humidity  wind_speed  solar_radiation
0  80.644932    4.814548        19.315781
1  81.466137    4.985205        17.853644
2  82.039151    5.304137        18.164493
3  81.762404    5.256749        18.200765
4  81.582603    5.188192        18.138466

In [221]:
# Clean merge keys

master_final["state_name"] = (
    master_final["state_name"]
    .astype(str)
    .str.strip()
    .str.upper()
)

master_final["district_name"] = (
    master_final["district_name"]
    .astype(str)
    .str.strip()
    .str.upper()
)

weather_yearly["State_Name"] = (
    weather_yearly["State_Name"]
    .astype(str)
    .str.strip()
    .str.upper()
)

weather_yearly["District_Name"] = (
    weather_yearly["District_Name"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [222]:
master_dataset = master_final.merge(
    weather_yearly,
    left_on=["state_name", "district_name", "year"],
    right_on=["State_Name", "District_Name", "year"],
    how="left"
)

In [223]:
print(master_dataset.shape)
print(master_dataset.columns.tolist())

(209086, 29)
['index', 'state_name', 'district_name', 'year', 'season', 'crop', 'area', 'production', 'Boron', 'Copper', 'Electrical Conductivity', 'Iron', 'Manganese', 'Nitrogen', 'Organic Carbon', 'Phosphorus', 'Potassium', 'Soil Ph', 'Sulphur', 'Zinc', 'State_Name_x', 'District_Name_x', 'State_Name_y', 'District_Name_y', 'temperature', 'rainfall', 'humidity', 'wind_speed', 'solar_radiation']

In [224]:
print(
    "State x vs State y:",
    (master_dataset["State_Name_x"] == master_dataset["State_Name_y"]).mean()
)

print(
    "District x vs District y:",
    (master_dataset["District_Name_x"] == master_dataset["District_Name_y"]).mean()
)

State x vs State y: 1.0
District x vs District y: 1.0

In [225]:
master_dataset.drop(
    columns=[
        "State_Name_x",
        "District_Name_x",
        "State_Name_y",
        "District_Name_y"
    ],
    inplace=True
)

In [226]:
print(
    master_dataset[
        [
            "temperature",
            "rainfall",
            "humidity",
            "wind_speed",
            "solar_radiation"
        ]
    ].isna().sum()
)

temperature        0
rainfall           0
humidity           0
wind_speed         0
solar_radiation    0
dtype: int64

In [227]:
master_dataset.drop(
    columns=["index"],
    inplace=True
)

In [228]:
print("Shape:", master_dataset.shape)

print("\nColumns:")
print(master_dataset.columns.tolist())

Shape: (209086, 24)

Columns:
['state_name', 'district_name', 'year', 'season', 'crop', 'area', 'production', 'Boron', 'Copper', 'Electrical Conductivity', 'Iron', 'Manganese', 'Nitrogen', 'Organic Carbon', 'Phosphorus', 'Potassium', 'Soil Ph', 'Sulphur', 'Zinc', 'temperature', 'rainfall', 'humidity', 'wind_speed', 'solar_radiation']

In [229]:
print(
    "Duplicate rows:",
    master_dataset.duplicated().sum()
)

Duplicate rows: 0

In [230]:
required_features = [
    "state_name",
    "district_name",
    "season",
    "Boron",
    "Copper",
    "Electrical Conductivity",
    "Iron",
    "Manganese",
    "Nitrogen",
    "Organic Carbon",
    "Phosphorus",
    "Potassium",
    "Soil Ph",
    "Sulphur",
    "Zinc",
    "temperature",
    "rainfall",
    "humidity",
    "wind_speed",
    "solar_radiation"
]

missing_features = [
    col for col in required_features
    if col not in master_dataset.columns
]

print("Missing model features:", missing_features)

Missing model features: []

In [231]:
master_dataset.to_csv(
    "../../data/processed/master_dataset.csv",
    index=False
)

print("master_dataset.csv saved successfully.")

master_dataset.csv saved successfully.

In [232]:
from pathlib import Path

path = Path("../../data/processed/master_dataset.csv")

print("File:", path.resolve())
print("Exists:", path.exists())
print("Size (MB):", round(path.stat().st_size / (1024 * 1024), 2))

File: D:\VS CODE SAVES\NTCC\KrishKalp\KrishiKalp-Smart-Crop-Recommendation-website-\data\processed\master_dataset.csv
Exists: True
Size (MB): 70.25

In [233]:
print("Final shape:", master_dataset.shape)

print("\nMissing values:")
print(master_dataset.isna().sum())

print("\nDuplicate rows:")
print(master_dataset.duplicated().sum())

print("\nUnique states:", master_dataset["state_name"].nunique())
print("Unique districts:", master_dataset["district_name"].nunique())
print("Unique crops:", master_dataset["crop"].nunique())
print("Unique years:", master_dataset["year"].nunique())
print("Unique seasons:", master_dataset["season"].nunique())

Final shape: (209086, 24)

Missing values:
state_name         0
district_name      0
year               0
season             0
crop               0
                  ..
temperature        0
rainfall           0
humidity           0
wind_speed         0
solar_radiation    0
Length: 24, dtype: int64

Duplicate rows:
0

Unique states: 30
Unique districts: 557
Unique crops: 123
Unique years: 19
Unique seasons: 6

In [235]:
import pandas as pd

crop_df = pd.read_csv(
    "../../data/raw/crop_production.csv"
)

print("Original crop production:", crop_df.shape)
print("Master final:", master_final.shape)
print("Final master:", master_dataset.shape)

Original crop production: (246091, 8)
Master final: (209086, 22)
Final master: (209086, 24)

In [237]:
crop_keys = crop_df[
    [
        "State_Name",
        "District_Name",
        "Crop_Year",
        "Season",
        "Crop"
    ]
].copy()

crop_keys.columns = [
    "state_name",
    "district_name",
    "year",
    "season",
    "crop"
]

# Normalize crop dataset keys
for col in ["state_name", "district_name", "season", "crop"]:
    crop_keys[col] = (
        crop_keys[col]
        .astype(str)
        .str.strip()
        .str.upper()
    )

# Normalize master keys
master_keys = master_dataset[
    [
        "state_name",
        "district_name",
        "year",
        "season",
        "crop"
    ]
].drop_duplicates().copy()

for col in ["state_name", "district_name", "season", "crop"]:
    master_keys[col] = (
        master_keys[col]
        .astype(str)
        .str.strip()
        .str.upper()
    )

# Make sure year has the same type
crop_keys["year"] = pd.to_numeric(
    crop_keys["year"],
    errors="coerce"
)

master_keys["year"] = pd.to_numeric(
    master_keys["year"],
    errors="coerce"
)

comparison = crop_keys.merge(
    master_keys,
    on=[
        "state_name",
        "district_name",
        "year",
        "season",
        "crop"
    ],
    how="left",
    indicator=True
)

print(comparison["_merge"].value_counts())

_merge
both          209086
left_only      37005
right_only         0
Name: count, dtype: int64

In [238]:
master_dataset.to_csv(
    "../../data/processed/master_dataset.csv",
    index=False
)

print("Master dataset saved successfully.")

Master dataset saved successfully.

In [239]:
check = pd.read_csv(
    "../../data/processed/master_dataset.csv"
)

print("Shape:", check.shape)
print("Missing values:", check.isna().sum().sum())
print("Duplicates:", check.duplicated().sum())

Shape: (209086, 24)
Missing values: 3405
Duplicates: 0

In [240]:
print(check.isna().sum())

state_name         0
district_name      0
year               0
season             0
crop               0
                  ..
temperature        0
rainfall           0
humidity           0
wind_speed         0
solar_radiation    0
Length: 24, dtype: int64

In [241]:
missing_rows = check[check.isna().any(axis=1)]

print("Rows with missing values:", len(missing_rows))
print(missing_rows.head())

Rows with missing values: 3405
                      state_name district_name  year       season  \
46   ANDAMAN AND NICOBAR ISLANDS      NICOBARS  2005  Whole Year
51   ANDAMAN AND NICOBAR ISLANDS      NICOBARS  2005  Whole Year
365               ANDHRA PRADESH      CHITTOOR  2001  Rabi
529               ANDHRA PRADESH      CHITTOOR  2004  Rabi
631               ANDHRA PRADESH      CHITTOOR  2007  Kharif

                  crop     area  production      Boron     Copper  \
46            Arecanut   795.67         NaN   7.070796   7.070796
51        Dry chillies    17.00         NaN   7.070796   7.070796
365              Wheat     4.00         NaN  12.343402  12.296900
529              Wheat     2.00         NaN  12.343402  12.296900
631  Moong(Green Gram)  1000.00         NaN  12.343402  12.296900

     Electrical Conductivity       Iron  Manganese  Nitrogen  Organic Carbon  \
46                  7.008772   7.070796   7.070796  4.727811        4.727811
51                  7.008772   7.070796   7.070796  4.727811        4.727811
365                12.337043  12.336248  12.333863  8.226020        8.228405
529                12.337043  12.336248  12.333863  8.226020        8.228405
631                12.337043  12.336248  12.333863  8.226020        8.228405

     Phosphorus  Potassium   Soil Ph    Sulphur       Zinc  temperature  \
46     4.727811   4.727811  4.727811   7.070796   7.070796    27.901288
51     4.727811   4.727811  4.727811   7.070796   7.070796    27.901288
365    8.231055   8.231055  8.216216  12.338633  12.327107    26.781918
529    8.231055   8.231055  8.216216  12.338633  12.327107    26.034454
631    8.231055   8.231055  8.216216  12.338633  12.327107    26.108932

     rainfall   humidity  wind_speed  solar_radiation
46    2100.41  81.884658    5.031151        18.240027
51    2100.41  81.884658    5.031151        18.240027
365    994.32  67.925753    2.561041        19.098192
529   1041.08  71.361175    2.433770        19.535410
631   1099.66  71.671096    2.266740        19.243781

In [242]:
missing = check.isna().sum()

print(missing[missing > 0])

production    3405
dtype: int64