In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

df = pd.read_csv("../../data/processed/master_dataset.csv")

print(df.shape)

df.head()

(449505, 25)

,state_name,district_name,year,season,crop,area,production,yield,Boron,Copper,...,Phosphorus,Potassium,Soil Ph,Sulphur,Zinc,temperature,rainfall,humidity,wind_speed,solar_radiation
0,ANDHRA PRADESH,CHITTOOR,1997,Kharif,Arhar/Tur,6100.0,900.0,0.147541,12.343402,12.2969,...,8.231055,8.231055,8.216216,12.338633,12.327107,24.919123,852.26,68.333205,2.833452,18.610904
1,ANDHRA PRADESH,CHITTOOR,1997,Kharif,Bajra,1700.0,1900.0,1.117647,12.343402,12.2969,...,8.231055,8.231055,8.216216,12.338633,12.327107,24.919123,852.26,68.333205,2.833452,18.610904
2,ANDHRA PRADESH,CHITTOOR,1997,Kharif,Dry chillies,600.0,800.0,1.333333,12.343402,12.2969,...,8.231055,8.231055,8.216216,12.338633,12.327107,24.919123,852.26,68.333205,2.833452,18.610904
3,ANDHRA PRADESH,CHITTOOR,1997,Kharif,Groundnut,234900.0,144200.0,0.613878,12.343402,12.2969,...,8.231055,8.231055,8.216216,12.338633,12.327107,24.919123,852.26,68.333205,2.833452,18.610904
4,ANDHRA PRADESH,CHITTOOR,1997,Kharif,Horse-gram,3100.0,2000.0,0.645161,12.343402,12.2969,...,8.231055,8.231055,8.216216,12.338633,12.327107,24.919123,852.26,68.333205,2.833452,18.610904

In [2]:
recommendation_df = (
    df.groupby(
        [
            "state_name",
            "district_name",
            "year",
            "season",
            "Boron",
            "Copper",
            "Electrical Conductivity",
            "Iron",
            "Manganese",
            "Nitrogen",
            "Organic Carbon",
            "Phosphorus",
            "Potassium",
            "Soil Ph",
            "Sulphur",
            "Zinc",
            "temperature",
            "rainfall",
            "humidity",
            "wind_speed",
            "solar_radiation",
        ]
    )
    .agg(
        {
            "crop": lambda x: list(sorted(set(x)))
        }
    )
    .reset_index()
)

In [3]:
print(recommendation_df.shape)

recommendation_df.head()

(39268, 22)

,state_name,district_name,year,season,Boron,Copper,Electrical Conductivity,Iron,Manganese,Nitrogen,...,Potassium,Soil Ph,Sulphur,Zinc,temperature,rainfall,humidity,wind_speed,solar_radiation,crop
0,ANDHRA PRADESH,CHITTOOR,1997,Kharif,12.343402,12.2969,12.337043,12.336248,12.333863,8.22602,...,8.231055,8.216216,12.338633,12.327107,24.919123,852.26,68.333205,2.833452,18.610904,"[Arhar/Tur, Bajra, Dry chillies, Groundnut, Ho..."
1,ANDHRA PRADESH,CHITTOOR,1997,Rabi,12.343402,12.2969,12.337043,12.336248,12.333863,8.22602,...,8.231055,8.216216,12.338633,12.327107,24.919123,852.26,68.333205,2.833452,18.610904,"[Dry chillies, Groundnut, Horse-gram, Ragi, Ri..."
2,ANDHRA PRADESH,CHITTOOR,1998,Kharif,12.343402,12.2969,12.337043,12.336248,12.333863,8.22602,...,8.231055,8.216216,12.338633,12.327107,24.993014,996.30,71.368685,2.713068,18.542027,"[Arhar/Tur, Bajra, Castor seed, Dry chillies, ..."
3,ANDHRA PRADESH,CHITTOOR,1998,Rabi,12.343402,12.2969,12.337043,12.336248,12.333863,8.22602,...,8.231055,8.216216,12.338633,12.327107,24.993014,996.30,71.368685,2.713068,18.542027,"[Dry chillies, Groundnut, Horse-gram, Maize, R..."
4,ANDHRA PRADESH,CHITTOOR,1998,Whole Year,12.343402,12.2969,12.337043,12.336248,12.333863,8.22602,...,8.231055,8.216216,12.338633,12.327107,24.993014,996.30,71.368685,2.713068,18.542027,[Sugarcane]

In [4]:
recommendation_df["num_crops"] = recommendation_df["crop"].apply(len)

recommendation_df["num_crops"].describe()

count    39268.000000
mean         7.047061
std          5.131894
min          1.000000
25%          2.000000
50%          6.000000
75%         10.000000
max         49.000000
Name: num_crops, dtype: float64

In [5]:
recommendation_df.loc[recommendation_df["num_crops"].idxmax()]

state_name                                                        TAMIL NADU
district_name                                                       DINDIGUL
year                                                                    2002
season                                                            Whole Year
Boron                                                              28.687943
Copper                                                             28.702128
Electrical Conductivity                                            28.515957
Iron                                                               28.730496
Manganese                                                           28.73227
Nitrogen                                                           19.085106
Organic Carbon                                                     19.061466
Phosphorus                                                         19.096927
Potassium                                                          19.122931
Soil Ph                                                            18.973995
Sulphur                                                            28.695035
Zinc                                                               28.712766
temperature                                                        25.552192
rainfall                                                              671.23
humidity                                                            68.53474
wind_speed                                                          2.701781
solar_radiation                                                    19.909726
crop                       [Apple, Banana, Beans & Mutter(Vegetable), Bee...
num_crops                                                                 49
Name: 31056, dtype: object

In [6]:
recommendation_df.loc[
    recommendation_df["num_crops"].idxmax(),
    "crop"
]

['Apple',
 'Banana',
 'Beans & Mutter(Vegetable)',
 'Beet Root',
 'Bhindi',
 'Bitter Gourd',
 'Bottle Gourd',
 'Brinjal',
 'Cabbage',
 'Carrot',
 'Cashewnut',
 'Cauliflower',
 'Citrus Fruit',
 'Coconut',
 'Coriander',
 'Cucumber',
 'Drum Stick',
 'Dry chillies',
 'Dry ginger',
 'Garlic',
 'Ginger',
 'Grapes',
 'Jack Fruit',
 'Lab-Lab',
 'Mango',
 'Onion',
 'Orange',
 'Other Citrus Fruit',
 'Other Fresh Fruits',
 'Other Vegetables',
 'Papaya',
 'Peach',
 'Pear',
 'Pineapple',
 'Plums',
 'Pome Fruit',
 'Pome Granet',
 'Potato',
 'Pump Kin',
 'Redish',
 'Snak Guard',
 'Sugarcane',
 'Sweet potato',
 'Tapioca',
 'Tobacco',
 'Tomato',
 'Turmeric',
 'Turnip',
 'Water Melon']

In [7]:
from collections import Counter

crop_counter = Counter()

for crops in recommendation_df["crop"]:
    crop_counter.update(crops)

crop_frequency = (
    pd.DataFrame(
        crop_counter.items(),
        columns=["crop", "count"]
    )
    .sort_values("count", ascending=False)
    .reset_index(drop=True)
)

crop_frequency.head(20)

                     crop  count
0                    Rice  16401
1                   Maize  15643
2       Moong(Green Gram)  11579
3                    Urad  11061
4                 Sesamum  10000
5               Groundnut   9456
6                   Wheat   8987
7               Sugarcane   8785
8       Rapeseed &Mustard   8716
9               Arhar/Tur   8503
10                  Onion   8411
11                 Potato   8380
12                   Gram   8173
13                  Jowar   7522
14           Dry chillies   6780
15                  Bajra   6333
16  Peas & beans (Pulses)   5785
17          Small millets   5402
18              Sunflower   5180
19                 Masoor   5161

In [8]:
crop_frequency.head(20)

                     crop  count
0                    Rice  16401
1                   Maize  15643
2       Moong(Green Gram)  11579
3                    Urad  11061
4                 Sesamum  10000
5               Groundnut   9456
6                   Wheat   8987
7               Sugarcane   8785
8       Rapeseed &Mustard   8716
9               Arhar/Tur   8503
10                  Onion   8411
11                 Potato   8380
12                   Gram   8173
13                  Jowar   7522
14           Dry chillies   6780
15                  Bajra   6333
16  Peas & beans (Pulses)   5785
17          Small millets   5402
18              Sunflower   5180
19                 Masoor   5161

In [9]:
len(crop_frequency)

126

In [11]:
environment_cols = [col for col in recommendation_no_year.columns if col not in ["crop", "num_crops"]]

print(recommendation_no_year.duplicated(subset=environment_cols).sum())

0

In [12]:
recommendation_df = recommendation_df.drop(columns=["year"])

In [13]:
print(recommendation_df.columns.tolist())

['state_name', 'district_name', 'season', 'Boron', 'Copper', 'Electrical Conductivity', 'Iron', 'Manganese', 'Nitrogen', 'Organic Carbon', 'Phosphorus', 'Potassium', 'Soil Ph', 'Sulphur', 'Zinc', 'temperature', 'rainfall', 'humidity', 'wind_speed', 'solar_radiation', 'crop', 'num_crops']

In [14]:
X = recommendation_df.drop(columns=["crop", "num_crops"])
y = recommendation_df["crop"]

print(X.shape)
print(y.shape)

(39268, 20)
(39268,)

In [15]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()

y_encoded = mlb.fit_transform(y)

print(y_encoded.shape)

(39268, 126)

In [16]:
print(mlb.classes_)

['Apple' 'Arcanut (Processed)' 'Arecanut' 'Arhar/Tur' 'Ash Gourd'
 'Atcanut (Raw)' 'Bajra' 'Banana' 'Barley' 'Bean'
 'Beans & Mutter(Vegetable)' 'Beet Root' 'Ber' 'Bhindi' 'Bitter Gourd'
 'Black pepper' 'Blackgram' 'Bottle Gourd' 'Brinjal' 'Cabbage' 'Cardamom'
 'Carrot' 'Cashewnut' 'Cashewnut Processed' 'Cashewnut Raw' 'Castor seed'
 'Cauliflower' 'Citrus Fruit' 'Coconut' 'Coffee' 'Colocosia'
 'Cond-spcs other' 'Coriander' 'Cotton(lint)' 'Cowpea(Lobia)' 'Cucumber'
 'Drum Stick' 'Dry chillies' 'Dry ginger' 'Garlic' 'Ginger' 'Gram'
 'Grapes' 'Groundnut' 'Guar seed' 'Horse-gram' 'Jack Fruit' 'Jobster'
 'Jowar' 'Jute' 'Jute & mesta' 'Kapas' 'Khesari' 'Korra' 'Lab-Lab' 'Lemon'
 'Lentil' 'Linseed' 'Litchi' 'Maize' 'Mango' 'Masoor' 'Mesta'
 'Moong(Green Gram)' 'Moth' 'Niger seed' 'Oilseeds total' 'Onion' 'Orange'
 'Other  Rabi pulses' 'Other Cereals' 'Other Cereals & Millets'
 'Other Citrus Fruit' 'Other Fresh Fruits' 'Other Kharif pulses'
 'Other Rabi pulses' 'Other Summer Pulses' 'Other Vegetables' 'Paddy'
 'Papaya' 'Peach' 'Pear' 'Peas  (vegetable)' 'Peas & beans (Pulses)'
 'Perilla' 'Pineapple' 'Plums' 'Pome Fruit' 'Pome Granet' 'Potato'
 'Pulses total' 'Pump Kin' 'Ragi' 'Rajmash Kholar' 'Rapeseed &Mustard'
 'Redish' 'Ribed Guard' 'Rice' 'Ricebean (nagadal)' 'Rubber' 'Safflower'
 'Samai' 'Sannhamp' 'Sapota' 'Sesamum' 'Small millets' 'Snak Guard'
 'Soyabean' 'Sugarcane' 'Sunflower' 'Sweet potato' 'Tapioca' 'Tea'
 'Tobacco' 'Tomato' 'Total foodgrain' 'Turmeric' 'Turnip' 'Urad' 'Varagu'
 'Water Melon' 'Wheat' 'Yam' 'other fibres' 'other misc. pulses'
 'other oilseeds']

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(31414, 20)
(7854, 20)
(31414, 126)
(7854, 126)

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

In [19]:
categorical_features = X_train.select_dtypes(include=["object"]).columns.tolist()
numerical_features = X_train.select_dtypes(exclude=["object"]).columns.tolist()

print("Categorical:", categorical_features)
print("\nNumerical:", numerical_features)

Categorical: ['state_name', 'district_name', 'season']

Numerical: ['Boron', 'Copper', 'Electrical Conductivity', 'Iron', 'Manganese', 'Nitrogen', 'Organic Carbon', 'Phosphorus', 'Potassium', 'Soil Ph', 'Sulphur', 'Zinc', 'temperature', 'rainfall', 'humidity', 'wind_speed', 'solar_radiation']

In [20]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("encoder", OneHotEncoder(handle_unknown="ignore"))
            ]),
            categorical_features
        ),
        (
            "num",
            Pipeline([
                ("imputer", SimpleImputer(strategy="median"))
            ]),
            numerical_features
        )
    ]
)

In [21]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(random_state=42)

In [22]:
from sklearn.multioutput import MultiOutputClassifier

dt_model = MultiOutputClassifier(
    DecisionTreeClassifier(random_state=42)
)

In [23]:
dt_model.fit(X_train, y_train)

ValueError: could not convert string to float: 'ARUNACHAL PRADESH'

In [24]:
from sklearn.pipeline import Pipeline

dt_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", MultiOutputClassifier(
        DecisionTreeClassifier(random_state=42)
    ))
])

In [25]:
dt_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['state_name',
                                                   'district_name', 'season']),
                                                 ('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Boron', 'Copper',
                                                   'Electrical Conductivity',
                                                   'Iron', 'Manganese',
                                                   'Nitrogen', 'Organic Carbon',
                                                   'Phosphorus', 'Potassium',
                                                   'Soil Ph', 'Sulphur', 'Zinc',
                                                   'temperature', 'rainfall',
                                                   'humidity', 'wind_speed',
                                                   'solar_radiation'])])),
                ('classifier',
                 MultiOutputClassifier(estimator=DecisionTreeClassifier(random_state=42)))])

In [26]:
from sklearn.metrics import hamming_loss

y_pred = dt_pipeline.predict(X_test)

print("Hamming Loss:", hamming_loss(y_test, y_pred))

Hamming Loss: 0.021630874572051043

In [27]:
from sklearn.metrics import f1_score

print("Micro F1:", f1_score(y_test, y_pred, average="micro"))

Micro F1: 0.8074376596739952

In [28]:
print("Macro F1:", f1_score(y_test, y_pred, average="macro"))

Macro F1: 0.500135125432248

In [29]:
results = pd.DataFrame({
    "Model": ["Decision Tree"],
    "Hamming Loss": [hamming_loss(y_test, y_pred)],
    "Micro F1": [f1_score(y_test, y_pred, average="micro")],
    "Macro F1": [f1_score(y_test, y_pred, average="macro")]
})

results

           Model  Hamming Loss  Micro F1  Macro F1
0  Decision Tree      0.021631  0.807438  0.500135

In [30]:
from sklearn.ensemble import RandomForestClassifier

In [31]:
from sklearn.pipeline import Pipeline
from sklearn.multioutput import MultiOutputClassifier

rf_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", MultiOutputClassifier(
        RandomForestClassifier(
            n_estimators=100,
            random_state=42,
            n_jobs=-1
        )
    ))
])

In [32]:
rf_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['state_name',
                                                   'district_name', 'season']),
                                                 ('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Boron', 'Copper',
                                                   'Electrical Conductivity',
                                                   'Iron', 'Manganese',
                                                   'Nitrogen', 'Organic Carbon',
                                                   'Phosphorus', 'Potassium',
                                                   'Soil Ph', 'Sulphur', 'Zinc',
                                                   'temperature', 'rainfall',
                                                   'humidity', 'wind_speed',
                                                   'solar_radiation'])])),
                ('classifier',
                 MultiOutputClassifier(estimator=RandomForestClassifier(n_jobs=-1,
                                                                        random_state=42)))])

In [33]:
from sklearn.metrics import hamming_loss, f1_score

y_pred_rf = rf_pipeline.predict(X_test)

print("Hamming Loss:", hamming_loss(y_test, y_pred_rf))
print("Micro F1:", f1_score(y_test, y_pred_rf, average="micro"))
print("Macro F1:", f1_score(y_test, y_pred_rf, average="macro"))

Hamming Loss: 0.01945121482936609
Micro F1: 0.8171898000854741
Macro F1: 0.34302658217001647

In [34]:
results.loc[len(results)] = [
    "Random Forest",
    hamming_loss(y_test, y_pred_rf),
    f1_score(y_test, y_pred_rf, average="micro"),
    f1_score(y_test, y_pred_rf, average="macro")
]

results

           Model  Hamming Loss  Micro F1  Macro F1
0  Decision Tree      0.021631  0.807438  0.500135
1  Random Forest      0.019451  0.817190  0.343027

In [35]:
from xgboost import XGBClassifier

In [36]:
xgb_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", MultiOutputClassifier(
        XGBClassifier(
            n_estimators=100,
            max_depth=6,
            learning_rate=0.1,
            random_state=42,
            n_jobs=-1,
            eval_metric="logloss"
        )
    ))
])

In [37]:
xgb_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['state_name',
                                                   'district_name', 'season']),
                                                 ('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Boron', 'Copper',
                                                   'Electrical Conductivity',
                                                   'Iro...
                                                               feature_weights=None,
                                                               gamma=None,
                                                               grow_policy=None,
                                                               importance_type=None,
                                                               interaction_constraints=None,
                                                               learning_rate=0.1,
                                                               max_bin=None,
                                                               max_cat_threshold=None,
                                                               max_cat_to_onehot=None,
                                                               max_delta_step=None,
                                                               max_depth=6,
                                                               max_leaves=None,
                                                               min_child_weight=None,
                                                               missing=nan,
                                                               monotone_constraints=None,
                                                               multi_strategy=None,
                                                               n_estimators=100,
                                                               n_jobs=-1,
                                                               num_parallel_tree=None, ...)))])

In [38]:
y_pred_xgb = xgb_pipeline.predict(X_test)

print("Hamming Loss:", hamming_loss(y_test, y_pred_xgb))
print("Micro F1:", f1_score(y_test, y_pred_xgb, average="micro"))
print("Macro F1:", f1_score(y_test, y_pred_xgb, average="macro"))

Hamming Loss: 0.019400689568756797
Micro F1: 0.8218768845386649
Macro F1: 0.45208845991649294

In [39]:
results.loc[len(results)] = [
    "XGBoost",
    hamming_loss(y_test, y_pred_xgb),
    f1_score(y_test, y_pred_xgb, average="micro"),
    f1_score(y_test, y_pred_xgb, average="macro")
]

results

           Model  Hamming Loss  Micro F1  Macro F1
0  Decision Tree      0.021631  0.807438  0.500135
1  Random Forest      0.019451  0.817190  0.343027
2        XGBoost      0.019401  0.821877  0.452088

In [40]:
from lightgbm import LGBMClassifier

In [41]:
lgbm_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", MultiOutputClassifier(
        LGBMClassifier(
            n_estimators=100,
            learning_rate=0.1,
            random_state=42,
            n_jobs=-1,
            verbose=-1
        )
    ))
])

In [42]:
lgbm_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['state_name',
                                                   'district_name', 'season']),
                                                 ('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Boron', 'Copper',
                                                   'Electrical Conductivity',
                                                   'Iron', 'Manganese',
                                                   'Nitrogen', 'Organic Carbon',
                                                   'Phosphorus', 'Potassium',
                                                   'Soil Ph', 'Sulphur', 'Zinc',
                                                   'temperature', 'rainfall',
                                                   'humidity', 'wind_speed',
                                                   'solar_radiation'])])),
                ('classifier',
                 MultiOutputClassifier(estimator=LGBMClassifier(n_jobs=-1,
                                                                random_state=42,
                                                                verbose=-1)))])

In [43]:
y_pred_lgbm = lgbm_pipeline.predict(X_test)

print("Hamming Loss:", hamming_loss(y_test, y_pred_lgbm))
print("Micro F1:", f1_score(y_test, y_pred_lgbm, average="micro"))
print("Macro F1:", f1_score(y_test, y_pred_lgbm, average="macro"))

Hamming Loss: 0.01824568211122833
Micro F1: 0.8353456137151195
Macro F1: 0.44660053190739407

In [44]:
results.loc[len(results)] = [
    "LightGBM",
    hamming_loss(y_test, y_pred_lgbm),
    f1_score(y_test, y_pred_lgbm, average="micro"),
    f1_score(y_test, y_pred_lgbm, average="macro")
]

results

           Model  Hamming Loss  Micro F1  Macro F1
0  Decision Tree      0.021631  0.807438  0.500135
1  Random Forest      0.019451  0.817190  0.343027
2        XGBoost      0.019401  0.821877  0.452088
3       LightGBM      0.018246  0.835346  0.446601

In [45]:
from catboost import CatBoostClassifier

In [46]:
cat_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", MultiOutputClassifier(
        CatBoostClassifier(
            iterations=100,
            learning_rate=0.1,
            depth=6,
            random_seed=42,
            verbose=0
        )
    ))
])

In [47]:
cat_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['state_name',
                                                   'district_name', 'season']),
                                                 ('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Boron', 'Copper',
                                                   'Electrical Conductivity',
                                                   'Iron', 'Manganese',
                                                   'Nitrogen', 'Organic Carbon',
                                                   'Phosphorus', 'Potassium',
                                                   'Soil Ph', 'Sulphur', 'Zinc',
                                                   'temperature', 'rainfall',
                                                   'humidity', 'wind_speed',
                                                   'solar_radiation'])])),
                ('classifier',
                 MultiOutputClassifier(estimator=CatBoostClassifier(depth=6, iterations=100, learning_rate=0.1, random_seed=42, verbose=0)))])

In [48]:
y_pred_cat = cat_pipeline.predict(X_test)

print("Hamming Loss:", hamming_loss(y_test, y_pred_cat))
print("Micro F1:", f1_score(y_test, y_pred_cat, average="micro"))
print("Macro F1:", f1_score(y_test, y_pred_cat, average="macro"))

Hamming Loss: 0.019715967194958793
Micro F1: 0.8179621388119163
Macro F1: 0.4462699439090651

In [49]:
results.loc[len(results)] = [
    "CatBoost",
    hamming_loss(y_test, y_pred_cat),
    f1_score(y_test, y_pred_cat, average="micro"),
    f1_score(y_test, y_pred_cat, average="macro")
]

results

           Model  Hamming Loss  Micro F1  Macro F1
0  Decision Tree      0.021631  0.807438  0.500135
1  Random Forest      0.019451  0.817190  0.343027
2        XGBoost      0.019401  0.821877  0.452088
3       LightGBM      0.018246  0.835346  0.446601
4       CatBoost      0.019716  0.817962  0.446270

In [50]:
from sklearn.neighbors import KNeighborsClassifier

In [51]:
knn_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", MultiOutputClassifier(
        KNeighborsClassifier(
            n_neighbors=5,
            weights="uniform"
        )
    ))
])

In [52]:
knn_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['state_name',
                                                   'district_name', 'season']),
                                                 ('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Boron', 'Copper',
                                                   'Electrical Conductivity',
                                                   'Iron', 'Manganese',
                                                   'Nitrogen', 'Organic Carbon',
                                                   'Phosphorus', 'Potassium',
                                                   'Soil Ph', 'Sulphur', 'Zinc',
                                                   'temperature', 'rainfall',
                                                   'humidity', 'wind_speed',
                                                   'solar_radiation'])])),
                ('classifier',
                 MultiOutputClassifier(estimator=KNeighborsClassifier()))])

In [53]:
y_pred_knn = knn_pipeline.predict(X_test)

print("Hamming Loss:", hamming_loss(y_test, y_pred_knn))
print("Micro F1:", f1_score(y_test, y_pred_knn, average="micro"))
print("Macro F1:", f1_score(y_test, y_pred_knn, average="macro"))

Hamming Loss: 0.05880534031794536
Micro F1: 0.18525466916809005
Macro F1: 0.0539785111920831

In [54]:
results.loc[len(results)] = [
    "KNN",
    hamming_loss(y_test, y_pred_knn),
    f1_score(y_test, y_pred_knn, average="micro"),
    f1_score(y_test, y_pred_knn, average="macro")
]

results

           Model  Hamming Loss  Micro F1  Macro F1
0  Decision Tree      0.021631  0.807438  0.500135
1  Random Forest      0.019451  0.817190  0.343027
2        XGBoost      0.019401  0.821877  0.452088
3       LightGBM      0.018246  0.835346  0.446601
4       CatBoost      0.019716  0.817962  0.446270
5            KNN      0.058805  0.185255  0.053979

In [55]:
from sklearn.linear_model import LogisticRegression

In [56]:
logreg_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", MultiOutputClassifier(
        LogisticRegression(
            max_iter=1000,
            random_state=42,
            n_jobs=-1
        )
    ))
])

In [57]:
logreg_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['state_name',
                                                   'district_name', 'season']),
                                                 ('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Boron', 'Copper',
                                                   'Electrical Conductivity',
                                                   'Iron', 'Manganese',
                                                   'Nitrogen', 'Organic Carbon',
                                                   'Phosphorus', 'Potassium',
                                                   'Soil Ph', 'Sulphur', 'Zinc',
                                                   'temperature', 'rainfall',
                                                   'humidity', 'wind_speed',
                                                   'solar_radiation'])])),
                ('classifier',
                 MultiOutputClassifier(estimator=LogisticRegression(max_iter=1000,
                                                                    n_jobs=-1,
                                                                    random_state=42)))])

In [58]:
y_pred_logreg = logreg_pipeline.predict(X_test)

print("Hamming Loss:", hamming_loss(y_test, y_pred_logreg))
print("Micro F1:", f1_score(y_test, y_pred_logreg, average="micro"))
print("Macro F1:", f1_score(y_test, y_pred_logreg, average="macro"))

Hamming Loss: 0.030804240888274503
Micro F1: 0.705394591878153
Macro F1: 0.28830053100305275

In [59]:
results.loc[len(results)] = [
    "Logistic Regression",
    hamming_loss(y_test, y_pred_logreg),
    f1_score(y_test, y_pred_logreg, average="micro"),
    f1_score(y_test, y_pred_logreg, average="macro")
]

results

                 Model  Hamming Loss  Micro F1  Macro F1
0        Decision Tree      0.021631  0.807438  0.500135
1        Random Forest      0.019451  0.817190  0.343027
2              XGBoost      0.019401  0.821877  0.452088
3             LightGBM      0.018246  0.835346  0.446601
4             CatBoost      0.019716  0.817962  0.446270
5                  KNN      0.058805  0.185255  0.053979
6  Logistic Regression      0.030804  0.705395  0.288301

In [60]:
from sklearn.svm import LinearSVC

In [61]:
svm_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", MultiOutputClassifier(
        LinearSVC(
            random_state=42,
            max_iter=5000
        )
    ))
])

In [62]:
svm_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['state_name',
                                                   'district_name', 'season']),
                                                 ('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Boron', 'Copper',
                                                   'Electrical Conductivity',
                                                   'Iron', 'Manganese',
                                                   'Nitrogen', 'Organic Carbon',
                                                   'Phosphorus', 'Potassium',
                                                   'Soil Ph', 'Sulphur', 'Zinc',
                                                   'temperature', 'rainfall',
                                                   'humidity', 'wind_speed',
                                                   'solar_radiation'])])),
                ('classifier',
                 MultiOutputClassifier(estimator=LinearSVC(max_iter=5000,
                                                           random_state=42)))])

In [63]:
y_pred_svm = svm_pipeline.predict(X_test)

print("Hamming Loss:", hamming_loss(y_test, y_pred_svm))
print("Micro F1:", f1_score(y_test, y_pred_svm, average="micro"))
print("Macro F1:", f1_score(y_test, y_pred_svm, average="macro"))

Hamming Loss: 0.026700579221587625
Micro F1: 0.7487949802728526
Macro F1: 0.3168040948590367

In [64]:
results.loc[len(results)] = [
    "Linear SVM",
    hamming_loss(y_test, y_pred_svm),
    f1_score(y_test, y_pred_svm, average="micro"),
    f1_score(y_test, y_pred_svm, average="macro")
]

results

                 Model  Hamming Loss  Micro F1  Macro F1
0        Decision Tree      0.021631  0.807438  0.500135
1        Random Forest      0.019451  0.817190  0.343027
2              XGBoost      0.019401  0.821877  0.452088
3             LightGBM      0.018246  0.835346  0.446601
4             CatBoost      0.019716  0.817962  0.446270
5                  KNN      0.058805  0.185255  0.053979
6  Logistic Regression      0.030804  0.705395  0.288301
7           Linear SVM      0.026701  0.748795  0.316804

In [65]:
lgbm_pipeline_tuned = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", MultiOutputClassifier(
        LGBMClassifier(
            n_estimators=300,
            learning_rate=0.05,
            num_leaves=31,
            random_state=42,
            n_jobs=-1,
            verbose=-1
        )
    ))
])

In [66]:
lgbm_pipeline_tuned.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['state_name',
                                                   'district_name', 'season']),
                                                 ('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Boron', 'Copper',
                                                   'Electrical Conductivity',
                                                   'Iron', 'Manganese',
                                                   'Nitrogen', 'Organic Carbon',
                                                   'Phosphorus', 'Potassium',
                                                   'Soil Ph', 'Sulphur', 'Zinc',
                                                   'temperature', 'rainfall',
                                                   'humidity', 'wind_speed',
                                                   'solar_radiation'])])),
                ('classifier',
                 MultiOutputClassifier(estimator=LGBMClassifier(learning_rate=0.05,
                                                                n_estimators=300,
                                                                n_jobs=-1,
                                                                random_state=42,
                                                                verbose=-1)))])

In [67]:
y_pred_lgbm_tuned = lgbm_pipeline_tuned.predict(X_test)

print("Hamming Loss:", hamming_loss(y_test, y_pred_lgbm_tuned))
print("Micro F1:", f1_score(y_test, y_pred_lgbm_tuned, average="micro"))
print("Macro F1:", f1_score(y_test, y_pred_lgbm_tuned, average="macro"))

Hamming Loss: 0.01722102982607184
Micro F1: 0.8440519765739385
Macro F1: 0.4767077716157656

In [68]:
results.loc[len(results)] = [
    "LightGBM (Tuned)",
    hamming_loss(y_test, y_pred_lgbm_tuned),
    f1_score(y_test, y_pred_lgbm_tuned, average="micro"),
    f1_score(y_test, y_pred_lgbm_tuned, average="macro")
]

results

                 Model  Hamming Loss  Micro F1  Macro F1
0        Decision Tree      0.021631  0.807438  0.500135
1        Random Forest      0.019451  0.817190  0.343027
2              XGBoost      0.019401  0.821877  0.452088
3             LightGBM      0.018246  0.835346  0.446601
4             CatBoost      0.019716  0.817962  0.446270
5                  KNN      0.058805  0.185255  0.053979
6  Logistic Regression      0.030804  0.705395  0.288301
7           Linear SVM      0.026701  0.748795  0.316804
8     LightGBM (Tuned)      0.017221  0.844052  0.476708

In [69]:
from sklearn.model_selection import KFold, cross_val_score

In [70]:
kf = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [71]:
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer, f1_score

In [72]:
micro_f1_scorer = make_scorer(
    f1_score,
    average="micro"
)

In [73]:
cv_results = cross_validate(
    lgbm_pipeline_tuned,
    X,
    y_encoded,
    cv=kf,
    scoring={"micro_f1": micro_f1_scorer},
    n_jobs=-1
)

print("Cross-validation Micro F1 scores:", cv_results["test_micro_f1"])
print("Mean Micro F1:", cv_results["test_micro_f1"].mean())
print("Std Dev:", cv_results["test_micro_f1"].std())

Cross-validation Micro F1 scores: [0.84380203 0.84491313 0.84526795 0.84341063 0.84323963]
Mean Micro F1: 0.8441266734929573
Std Dev: 0.0008155946890017872

In [74]:
import joblib

joblib.dump(lgbm_pipeline_tuned, "lightgbm_tuned_crop_recommender.pkl")

['lightgbm_tuned_crop_recommender.pkl']

In [75]:
joblib.dump(mlb, "multilabel_binarizer.pkl")

['multilabel_binarizer.pkl']

In [76]:
loaded_model = joblib.load("lightgbm_tuned_crop_recommender.pkl")
loaded_mlb = joblib.load("multilabel_binarizer.pkl")

In [77]:
sample_input = X.iloc[[0]]

prediction = loaded_model.predict(sample_input)

In [78]:
recommended_crops = loaded_mlb.inverse_transform(prediction)

print("Recommended Crops:")
print(recommended_crops[0])

Recommended Crops:
('Arhar/Tur', 'Bajra', 'Castor seed', 'Cotton(lint)', 'Dry chillies', 'Groundnut', 'Horse-gram', 'Jowar', 'Maize', 'Moong(Green Gram)', 'Onion', 'Other Kharif pulses', 'Ragi', 'Rice', 'Samai', 'Sesamum', 'Small millets', 'Sunflower', 'Urad')

In [79]:
print("Actual Crops:")
print(y.iloc[0])

print("\nPredicted Crops:")
print(recommended_crops[0])

Actual Crops:
['Arhar/Tur', 'Bajra', 'Dry chillies', 'Groundnut', 'Horse-gram', 'Jowar', 'Maize', 'Moong(Green Gram)', 'Other Kharif pulses', 'Ragi', 'Rice', 'Samai', 'Sesamum', 'Sugarcane', 'Sunflower']

Predicted Crops:
('Arhar/Tur', 'Bajra', 'Castor seed', 'Cotton(lint)', 'Dry chillies', 'Groundnut', 'Horse-gram', 'Jowar', 'Maize', 'Moong(Green Gram)', 'Onion', 'Other Kharif pulses', 'Ragi', 'Rice', 'Samai', 'Sesamum', 'Small millets', 'Sunflower', 'Urad')

In [80]:
def recommend_crops(input_df):
    prediction = loaded_model.predict(input_df)
    return loaded_mlb.inverse_transform(prediction)[0]

In [81]:
recommend_crops(sample_input)

('Arhar/Tur',
 'Bajra',
 'Castor seed',
 'Cotton(lint)',
 'Dry chillies',
 'Groundnut',
 'Horse-gram',
 'Jowar',
 'Maize',
 'Moong(Green Gram)',
 'Onion',
 'Other Kharif pulses',
 'Ragi',
 'Rice',
 'Samai',
 'Sesamum',
 'Small millets',
 'Sunflower',
 'Urad')

In [82]:
print(X.columns.tolist())

['state_name', 'district_name', 'season', 'Boron', 'Copper', 'Electrical Conductivity', 'Iron', 'Manganese', 'Nitrogen', 'Organic Carbon', 'Phosphorus', 'Potassium', 'Soil Ph', 'Sulphur', 'Zinc', 'temperature', 'rainfall', 'humidity', 'wind_speed', 'solar_radiation']